from rivergis import river_database as rdb
baza = rdb.RiverDatabase('rivergis', 'localhost', '5432', 'postgres', 'pass')
baza.connect_pg()
sc = baza.process_hecobject(rdb.StreamCenterlines, 'pg_create_table', 'start', 2180)
xs = baza.process_hecobject(rdb.XSCutLines, 'pg_create_table', 'start', 2180)
bl = baza.process_hecobject(rdb.BankLines, 'pg_create_table', 'start', 2180)
la = baza.process_hecobject(rdb.LeveeAlignment, 'pg_create_table', 'start', 2180)
fp = baza.process_hecobject(rdb.Flowpaths, 'pg_create_table', 'start', 2180)
lu = baza.process_hecobject(rdb.LanduseAreas, 'pg_create_table', 'start', 2180)

baza.add_to_view(sc)
baza.add_to_view(xs)
baza.add_to_view(bl)
baza.add_to_view(la)
baza.add_to_view(fp)
baza.add_to_view(lu)
