GRANT USAGE ON SCHEMA example TO uzytkownicy;
ALTER DEFAULT PRIVILEGES IN SCHEMA example GRANT ALL ON TABLES TO uzytkownicy;
ALTER DEFAULT PRIVILEGES IN SCHEMA example GRANT ALL ON SEQUENCES TO uzytkownicy;
ALTER DEFAULT PRIVILEGES IN SCHEMA example GRANT EXECUTE ON FUNCTIONS TO uzytkownicy;