# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/ui_rivergis.ui'
#
# Created: Tue Nov 03 16:48:16 2015
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui
from qgis.gui import QgsProjectionSelectionWidget
from ..resources import *

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_RiverGIS(object):
    def setupUi(self, RiverGIS):
        RiverGIS.setObjectName(_fromUtf8("RiverGIS"))
        RiverGIS.setEnabled(True)
        RiverGIS.resize(586, 438)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/rivergis/icons/rivergis_big.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        RiverGIS.setWindowIcon(icon)
        RiverGIS.setIconSize(QtCore.QSize(24, 24))
        self.centralwidget = QtGui.QWidget(RiverGIS)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout_2 = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.labelCurSchema = QtGui.QLabel(self.centralwidget)
        self.labelCurSchema.setObjectName(_fromUtf8("labelCurSchema"))
        self.gridLayout.addWidget(self.labelCurSchema, 0, 3, 1, 1)
        self.labelCurDatabase = QtGui.QLabel(self.centralwidget)
        self.labelCurDatabase.setObjectName(_fromUtf8("labelCurDatabase"))
        self.gridLayout.addWidget(self.labelCurDatabase, 0, 0, 1, 1)
        self.schemasCbo = QtGui.QComboBox(self.centralwidget)
        self.schemasCbo.setMinimumSize(QtCore.QSize(200, 0))
        self.schemasCbo.setObjectName(_fromUtf8("schemasCbo"))
        self.gridLayout.addWidget(self.schemasCbo, 0, 4, 1, 1)
        self.connsCbo = QtGui.QComboBox(self.centralwidget)
        self.connsCbo.setMinimumSize(QtCore.QSize(200, 0))
        self.connsCbo.setObjectName(_fromUtf8("connsCbo"))
        self.gridLayout.addWidget(self.connsCbo, 0, 1, 1, 1)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem, 0, 2, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.textEdit = QtGui.QTextEdit(self.centralwidget)
        self.textEdit.setReadOnly(True)
        self.textEdit.setObjectName(_fromUtf8("textEdit"))
        self.gridLayout_2.addWidget(self.textEdit, 1, 0, 1, 1)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout.addWidget(self.label)
        self.crsWidget = QgsProjectionSelectionWidget(self.centralwidget)
        self.crsWidget.setMinimumSize(QtCore.QSize(300, 0))
        self.crsWidget.setMaximumSize(QtCore.QSize(400, 16777215))
        self.crsWidget.setObjectName(_fromUtf8("crsWidget"))
        self.horizontalLayout.addWidget(self.crsWidget)
        self.gridLayout_2.addLayout(self.horizontalLayout, 2, 0, 1, 1)
        RiverGIS.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(RiverGIS)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 586, 18))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setObjectName(_fromUtf8("menuHelp"))
        self.menu_Geometry = QtGui.QMenu(self.menubar)
        self.menu_Geometry.setObjectName(_fromUtf8("menu_Geometry"))
        self.menuXS_Cut_Line_Attributes = QtGui.QMenu(self.menu_Geometry)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/rivergis/icons/ras1dXs.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.menuXS_Cut_Line_Attributes.setIcon(icon1)
        self.menuXS_Cut_Line_Attributes.setObjectName(_fromUtf8("menuXS_Cut_Line_Attributes"))
        self.menuStreamCenterlineAttributes = QtGui.QMenu(self.menu_Geometry)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/rivergis/icons/ras1dStreamCenterlines.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.menuStreamCenterlineAttributes.setIcon(icon2)
        self.menuStreamCenterlineAttributes.setObjectName(_fromUtf8("menuStreamCenterlineAttributes"))
        self.menuBridges_Culverts = QtGui.QMenu(self.menu_Geometry)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/rivergis/icons/ras1dBridges.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.menuBridges_Culverts.setIcon(icon3)
        self.menuBridges_Culverts.setObjectName(_fromUtf8("menuBridges_Culverts"))
        self.menuInline_Structures = QtGui.QMenu(self.menu_Geometry)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8(":/rivergis/icons/ras1dInlineStruct.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.menuInline_Structures.setIcon(icon4)
        self.menuInline_Structures.setObjectName(_fromUtf8("menuInline_Structures"))
        self.menuLateral_Structures = QtGui.QMenu(self.menu_Geometry)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8(":/rivergis/icons/ras1dLateralStruct.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.menuLateral_Structures.setIcon(icon5)
        self.menuLateral_Structures.setObjectName(_fromUtf8("menuLateral_Structures"))
        self.menuStorage_Areas = QtGui.QMenu(self.menu_Geometry)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8(":/rivergis/icons/ras1dStorageAreas.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.menuStorage_Areas.setIcon(icon6)
        self.menuStorage_Areas.setObjectName(_fromUtf8("menuStorage_Areas"))
        self.menuStorage_Areas_Connections = QtGui.QMenu(self.menu_Geometry)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(_fromUtf8(":/rivergis/icons/ras1dSAConnections.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.menuStorage_Areas_Connections.setIcon(icon7)
        self.menuStorage_Areas_Connections.setObjectName(_fromUtf8("menuStorage_Areas_Connections"))
        self.menuDB = QtGui.QMenu(self.menubar)
        self.menuDB.setObjectName(_fromUtf8("menuDB"))
        self.menuSettings = QtGui.QMenu(self.menubar)
        self.menuSettings.setObjectName(_fromUtf8("menuSettings"))
        RiverGIS.setMenuBar(self.menubar)
        self.dbToolBar = QtGui.QToolBar(RiverGIS)
        self.dbToolBar.setObjectName(_fromUtf8("dbToolBar"))
        RiverGIS.addToolBar(QtCore.Qt.TopToolBarArea, self.dbToolBar)
        self.settingsToolBar = QtGui.QToolBar(RiverGIS)
        self.settingsToolBar.setObjectName(_fromUtf8("settingsToolBar"))
        RiverGIS.addToolBar(QtCore.Qt.TopToolBarArea, self.settingsToolBar)
        self.rasGeomToolBar = QtGui.QToolBar(RiverGIS)
        self.rasGeomToolBar.setObjectName(_fromUtf8("rasGeomToolBar"))
        RiverGIS.addToolBar(QtCore.Qt.TopToolBarArea, self.rasGeomToolBar)
        self.rasImportExportToolBar = QtGui.QToolBar(RiverGIS)
        self.rasImportExportToolBar.setObjectName(_fromUtf8("rasImportExportToolBar"))
        RiverGIS.addToolBar(QtCore.Qt.TopToolBarArea, self.rasImportExportToolBar)
        self.rasOptGeomToolBar = QtGui.QToolBar(RiverGIS)
        self.rasOptGeomToolBar.setObjectName(_fromUtf8("rasOptGeomToolBar"))
        RiverGIS.addToolBar(QtCore.Qt.TopToolBarArea, self.rasOptGeomToolBar)
        RiverGIS.insertToolBarBreak(self.rasOptGeomToolBar)
        self.rasStructuresToolBar = QtGui.QToolBar(RiverGIS)
        self.rasStructuresToolBar.setObjectName(_fromUtf8("rasStructuresToolBar"))
        RiverGIS.addToolBar(QtCore.Qt.TopToolBarArea, self.rasStructuresToolBar)
        self.rasSAToolBar = QtGui.QToolBar(RiverGIS)
        self.rasSAToolBar.setObjectName(_fromUtf8("rasSAToolBar"))
        RiverGIS.addToolBar(QtCore.Qt.TopToolBarArea, self.rasSAToolBar)
        self.ras2dToolBar = QtGui.QToolBar(RiverGIS)
        self.ras2dToolBar.setObjectName(_fromUtf8("ras2dToolBar"))
        RiverGIS.addToolBar(QtCore.Qt.TopToolBarArea, self.ras2dToolBar)
        self.actionRASCreate2dAreaPoints = QtGui.QAction(RiverGIS)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(_fromUtf8(":/rivergis/icons/ras2dareaCreate.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionRASCreate2dAreaPoints.setIcon(icon8)
        self.actionRASCreate2dAreaPoints.setObjectName(_fromUtf8("actionRASCreate2dAreaPoints"))
        self.actionHelpContents = QtGui.QAction(RiverGIS)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(_fromUtf8(":/rivergis/icons/helpContents.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionHelpContents.setIcon(icon9)
        self.actionHelpContents.setObjectName(_fromUtf8("actionHelpContents"))
        self.actionRASWaterSurfaceGeneration = QtGui.QAction(RiverGIS)
        self.actionRASWaterSurfaceGeneration.setEnabled(True)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(_fromUtf8(":/rivergis/icons/createWselRaster.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionRASWaterSurfaceGeneration.setIcon(icon10)
        self.actionRASWaterSurfaceGeneration.setObjectName(_fromUtf8("actionRASWaterSurfaceGeneration"))
        self.actionRefreshConnections = QtGui.QAction(RiverGIS)
        icon11 = QtGui.QIcon()
        icon11.addPixmap(QtGui.QPixmap(_fromUtf8(":/rivergis/icons/refreshConnections.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionRefreshConnections.setIcon(icon11)
        self.actionRefreshConnections.setObjectName(_fromUtf8("actionRefreshConnections"))
        self.actionRASSave2DPointsToHECRASGeometry = QtGui.QAction(RiverGIS)
        icon12 = QtGui.QIcon()
        icon12.addPixmap(QtGui.QPixmap(_fromUtf8(":/rivergis/icons/ras2dareaSaveToGeo.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionRASSave2DPointsToHECRASGeometry.setIcon(icon12)
        self.actionRASSave2DPointsToHECRASGeometry.setObjectName(_fromUtf8("actionRASSave2DPointsToHECRASGeometry"))
        self.actionRASPreview2DMesh = QtGui.QAction(RiverGIS)
        self.actionRASPreview2DMesh.setEnabled(True)
        icon13 = QtGui.QIcon()
        icon13.addPixmap(QtGui.QPixmap(_fromUtf8(":/rivergis/icons/ras2dareaPreview.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionRASPreview2DMesh.setIcon(icon13)
        self.actionRASPreview2DMesh.setObjectName(_fromUtf8("actionRASPreview2DMesh"))
        self.actionRASCreateRdbTables = QtGui.QAction(RiverGIS)
        icon14 = QtGui.QIcon()
        icon14.addPixmap(QtGui.QPixmap(_fromUtf8(":/rivergis/icons/createPgTables.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionRASCreateRdbTables.setIcon(icon14)
        self.actionRASCreateRdbTables.setObjectName(_fromUtf8("actionRASCreateRdbTables"))
        self.actionRASManningsNValues = QtGui.QAction(RiverGIS)
        icon15 = QtGui.QIcon()
        icon15.addPixmap(QtGui.QPixmap(_fromUtf8(":/rivergis/icons/ras1dXsMannings.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionRASManningsNValues.setIcon(icon15)
        self.actionRASManningsNValues.setObjectName(_fromUtf8("actionRASManningsNValues"))
        self.actionRASCreateRASGISImport = QtGui.QAction(RiverGIS)
        icon16 = QtGui.QIcon()
        icon16.addPixmap(QtGui.QPixmap(_fromUtf8(":/rivergis/icons/ras1dCreateRASImport.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionRASCreateRASGISImport.setIcon(icon16)
        self.actionRASCreateRASGISImport.setObjectName(_fromUtf8("actionRASCreateRASGISImport"))
        self.actionRASTopology1D = QtGui.QAction(RiverGIS)
        icon17 = QtGui.QIcon()
        icon17.addPixmap(QtGui.QPixmap(_fromUtf8(":/rivergis/icons/ras1dStreamCenterlinesTopology.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionRASTopology1D.setIcon(icon17)
        self.actionRASTopology1D.setObjectName(_fromUtf8("actionRASTopology1D"))
        self.actionRASLengthsStations = QtGui.QAction(RiverGIS)
        icon18 = QtGui.QIcon()
        icon18.addPixmap(QtGui.QPixmap(_fromUtf8(":/rivergis/icons/ras1dStreamCenterlinesLengthsStations.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionRASLengthsStations.setIcon(icon18)
        self.actionRASLengthsStations.setObjectName(_fromUtf8("actionRASLengthsStations"))
        self.actionRASStreamCenterlineAll = QtGui.QAction(RiverGIS)
        icon19 = QtGui.QIcon()
        icon19.addPixmap(QtGui.QPixmap(_fromUtf8(":/rivergis/icons/ras1dStreamCenterlinesAll.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionRASStreamCenterlineAll.setIcon(icon19)
        self.actionRASStreamCenterlineAll.setObjectName(_fromUtf8("actionRASStreamCenterlineAll"))
        self.actionRASXSRiverReachNames = QtGui.QAction(RiverGIS)
        icon20 = QtGui.QIcon()
        icon20.addPixmap(QtGui.QPixmap(_fromUtf8(":/rivergis/icons/ras1dXsRiverNames.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionRASXSRiverReachNames.setIcon(icon20)
        self.actionRASXSRiverReachNames.setObjectName(_fromUtf8("actionRASXSRiverReachNames"))
        self.actionRASXSStationing = QtGui.QAction(RiverGIS)
        icon21 = QtGui.QIcon()
        icon21.addPixmap(QtGui.QPixmap(_fromUtf8(":/rivergis/icons/ras1dXsStationing.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionRASXSStationing.setIcon(icon21)
        self.actionRASXSStationing.setObjectName(_fromUtf8("actionRASXSStationing"))
        self.actionRASXSBankStations = QtGui.QAction(RiverGIS)
        icon22 = QtGui.QIcon()
        icon22.addPixmap(QtGui.QPixmap(_fromUtf8(":/rivergis/icons/ras1dXsBanks.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionRASXSBankStations.setIcon(icon22)
        self.actionRASXSBankStations.setObjectName(_fromUtf8("actionRASXSBankStations"))
        self.actionRASXSDownstreamReachLengths = QtGui.QAction(RiverGIS)
        icon23 = QtGui.QIcon()
        icon23.addPixmap(QtGui.QPixmap(_fromUtf8(":/rivergis/icons/ras1dXsDSLenghts.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionRASXSDownstreamReachLengths.setIcon(icon23)
        self.actionRASXSDownstreamReachLengths.setObjectName(_fromUtf8("actionRASXSDownstreamReachLengths"))
        self.actionRASXSElevations = QtGui.QAction(RiverGIS)
        icon24 = QtGui.QIcon()
        icon24.addPixmap(QtGui.QPixmap(_fromUtf8(":/rivergis/icons/ras1dXsElevations.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionRASXSElevations.setIcon(icon24)
        self.actionRASXSElevations.setObjectName(_fromUtf8("actionRASXSElevations"))
        self.actionRASXSAll = QtGui.QAction(RiverGIS)
        icon25 = QtGui.QIcon()
        icon25.addPixmap(QtGui.QPixmap(_fromUtf8(":/rivergis/icons/ras1dXsAll.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionRASXSAll.setIcon(icon25)
        self.actionRASXSAll.setObjectName(_fromUtf8("actionRASXSAll"))
        self.actionRASImportLayersIntoRdbTables = QtGui.QAction(RiverGIS)
        icon26 = QtGui.QIcon()
        icon26.addPixmap(QtGui.QPixmap(_fromUtf8(":/rivergis/icons/importLayersIntoRdb.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionRASImportLayersIntoRdbTables.setIcon(icon26)
        self.actionRASImportLayersIntoRdbTables.setObjectName(_fromUtf8("actionRASImportLayersIntoRdbTables"))
        self.actionRASLevees = QtGui.QAction(RiverGIS)
        icon27 = QtGui.QIcon()
        icon27.addPixmap(QtGui.QPixmap(_fromUtf8(":/rivergis/icons/ras1dXsLevees.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionRASLevees.setIcon(icon27)
        self.actionRASLevees.setObjectName(_fromUtf8("actionRASLevees"))
        self.actionRASIneffectiveFlowAreas = QtGui.QAction(RiverGIS)
        icon28 = QtGui.QIcon()
        icon28.addPixmap(QtGui.QPixmap(_fromUtf8(":/rivergis/icons/ras1dXsIneffective.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionRASIneffectiveFlowAreas.setIcon(icon28)
        self.actionRASIneffectiveFlowAreas.setObjectName(_fromUtf8("actionRASIneffectiveFlowAreas"))
        self.actionRASBlockedObstructions = QtGui.QAction(RiverGIS)
        icon29 = QtGui.QIcon()
        icon29.addPixmap(QtGui.QPixmap(_fromUtf8(":/rivergis/icons/ras1dXsBlockedObs.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionRASBlockedObstructions.setIcon(icon29)
        self.actionRASBlockedObstructions.setObjectName(_fromUtf8("actionRASBlockedObstructions"))
        self.actionRASLoadRdbTablesIntoQGIS = QtGui.QAction(RiverGIS)
        icon30 = QtGui.QIcon()
        icon30.addPixmap(QtGui.QPixmap(_fromUtf8(":/rivergis/icons/loadRdbTablesIntoQgis.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionRASLoadRdbTablesIntoQGIS.setIcon(icon30)
        self.actionRASLoadRdbTablesIntoQGIS.setObjectName(_fromUtf8("actionRASLoadRdbTablesIntoQGIS"))
        self.actionOptions = QtGui.QAction(RiverGIS)
        icon31 = QtGui.QIcon()
        icon31.addPixmap(QtGui.QPixmap(_fromUtf8(":/rivergis/icons/options.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionOptions.setIcon(icon31)
        self.actionOptions.setObjectName(_fromUtf8("actionOptions"))
        self.actionDebugMode = QtGui.QAction(RiverGIS)
        self.actionDebugMode.setCheckable(True)
        self.actionDebugMode.setChecked(False)
        self.actionDebugMode.setObjectName(_fromUtf8("actionDebugMode"))
        self.actionCopyStreamCenterlines2Flowpaths = QtGui.QAction(RiverGIS)
        self.actionCopyStreamCenterlines2Flowpaths.setObjectName(_fromUtf8("actionCopyStreamCenterlines2Flowpaths"))
        self.actionAlwaysOnTop = QtGui.QAction(RiverGIS)
        self.actionAlwaysOnTop.setCheckable(True)
        self.actionAlwaysOnTop.setObjectName(_fromUtf8("actionAlwaysOnTop"))
        self.actionRASXSUpdateInsertMeasuredPoints = QtGui.QAction(RiverGIS)
        icon32 = QtGui.QIcon()
        icon32.addPixmap(QtGui.QPixmap(_fromUtf8(":/rivergis/icons/ras1dXsUpdate.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionRASXSUpdateInsertMeasuredPoints.setIcon(icon32)
        self.actionRASXSUpdateInsertMeasuredPoints.setObjectName(_fromUtf8("actionRASXSUpdateInsertMeasuredPoints"))
        self.actionRASBRRiverReachNames = QtGui.QAction(RiverGIS)
        self.actionRASBRRiverReachNames.setObjectName(_fromUtf8("actionRASBRRiverReachNames"))
        self.actionRASBRStationing = QtGui.QAction(RiverGIS)
        self.actionRASBRStationing.setObjectName(_fromUtf8("actionRASBRStationing"))
        self.actionRASBRElevations = QtGui.QAction(RiverGIS)
        self.actionRASBRElevations.setEnabled(True)
        self.actionRASBRElevations.setObjectName(_fromUtf8("actionRASBRElevations"))
        self.actionRASBRAll = QtGui.QAction(RiverGIS)
        self.actionRASBRAll.setIcon(icon3)
        self.actionRASBRAll.setObjectName(_fromUtf8("actionRASBRAll"))
        self.actionRASInlRiverReachNames = QtGui.QAction(RiverGIS)
        self.actionRASInlRiverReachNames.setObjectName(_fromUtf8("actionRASInlRiverReachNames"))
        self.actionRASInlStationing = QtGui.QAction(RiverGIS)
        self.actionRASInlStationing.setObjectName(_fromUtf8("actionRASInlStationing"))
        self.actionRASInlElevations = QtGui.QAction(RiverGIS)
        self.actionRASInlElevations.setEnabled(True)
        self.actionRASInlElevations.setObjectName(_fromUtf8("actionRASInlElevations"))
        self.actionRASInlAll = QtGui.QAction(RiverGIS)
        self.actionRASInlAll.setIcon(icon4)
        self.actionRASInlAll.setObjectName(_fromUtf8("actionRASInlAll"))
        self.actionRASLatRiverReachNames = QtGui.QAction(RiverGIS)
        self.actionRASLatRiverReachNames.setObjectName(_fromUtf8("actionRASLatRiverReachNames"))
        self.actionRASLatStationing = QtGui.QAction(RiverGIS)
        self.actionRASLatStationing.setObjectName(_fromUtf8("actionRASLatStationing"))
        self.actionRASLatElevations = QtGui.QAction(RiverGIS)
        self.actionRASLatElevations.setEnabled(True)
        self.actionRASLatElevations.setObjectName(_fromUtf8("actionRASLatElevations"))
        self.actionRASLatAll = QtGui.QAction(RiverGIS)
        self.actionRASLatAll.setIcon(icon5)
        self.actionRASLatAll.setObjectName(_fromUtf8("actionRASLatAll"))
        self.actionRASSAElevationVolumeData = QtGui.QAction(RiverGIS)
        icon33 = QtGui.QIcon()
        icon33.addPixmap(QtGui.QPixmap(_fromUtf8(":/rivergis/icons/ras1dSAElevVolume.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionRASSAElevationVolumeData.setIcon(icon33)
        self.actionRASSAElevationVolumeData.setObjectName(_fromUtf8("actionRASSAElevationVolumeData"))
        self.actionRASSATerrainPointExtraction = QtGui.QAction(RiverGIS)
        icon34 = QtGui.QIcon()
        icon34.addPixmap(QtGui.QPixmap(_fromUtf8(":/rivergis/icons/ras1dSATerPtExtract.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionRASSATerrainPointExtraction.setIcon(icon34)
        self.actionRASSATerrainPointExtraction.setObjectName(_fromUtf8("actionRASSATerrainPointExtraction"))
        self.actionRASSAAll = QtGui.QAction(RiverGIS)
        self.actionRASSAAll.setIcon(icon6)
        self.actionRASSAAll.setObjectName(_fromUtf8("actionRASSAAll"))
        self.actionRASSacAssignNearestSA = QtGui.QAction(RiverGIS)
        self.actionRASSacAssignNearestSA.setObjectName(_fromUtf8("actionRASSacAssignNearestSA"))
        self.actionRASSacElevations = QtGui.QAction(RiverGIS)
        self.actionRASSacElevations.setObjectName(_fromUtf8("actionRASSacElevations"))
        self.actionRASSacAll = QtGui.QAction(RiverGIS)
        self.actionRASSacAll.setIcon(icon7)
        self.actionRASSacAll.setObjectName(_fromUtf8("actionRASSacAll"))
        self.actionWebsite = QtGui.QAction(RiverGIS)
        icon35 = QtGui.QIcon()
        icon35.addPixmap(QtGui.QPixmap(_fromUtf8(":/rivergis/icons/webSite.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionWebsite.setIcon(icon35)
        self.actionWebsite.setObjectName(_fromUtf8("actionWebsite"))
        self.actionAbout = QtGui.QAction(RiverGIS)
        icon36 = QtGui.QIcon()
        icon36.addPixmap(QtGui.QPixmap(_fromUtf8(":/rivergis/icons/rivergis.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionAbout.setIcon(icon36)
        self.actionAbout.setObjectName(_fromUtf8("actionAbout"))
        self.actionRestoreDefaultOptions = QtGui.QAction(RiverGIS)
        self.actionRestoreDefaultOptions.setObjectName(_fromUtf8("actionRestoreDefaultOptions"))
        self.actionCreateNewSchema = QtGui.QAction(RiverGIS)
        icon37 = QtGui.QIcon()
        icon37.addPixmap(QtGui.QPixmap(_fromUtf8(":/rivergis/icons/dbCreateSchema.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionCreateNewSchema.setIcon(icon37)
        self.actionCreateNewSchema.setObjectName(_fromUtf8("actionCreateNewSchema"))
        self.menuHelp.addAction(self.actionHelpContents)
        self.menuHelp.addAction(self.actionWebsite)
        self.menuHelp.addAction(self.actionAbout)
        self.menuXS_Cut_Line_Attributes.addAction(self.actionRASXSRiverReachNames)
        self.menuXS_Cut_Line_Attributes.addAction(self.actionRASXSStationing)
        self.menuXS_Cut_Line_Attributes.addAction(self.actionRASXSBankStations)
        self.menuXS_Cut_Line_Attributes.addAction(self.actionRASXSDownstreamReachLengths)
        self.menuXS_Cut_Line_Attributes.addSeparator()
        self.menuXS_Cut_Line_Attributes.addAction(self.actionRASXSElevations)
        self.menuXS_Cut_Line_Attributes.addSeparator()
        self.menuXS_Cut_Line_Attributes.addAction(self.actionRASXSAll)
        self.menuXS_Cut_Line_Attributes.addSeparator()
        self.menuXS_Cut_Line_Attributes.addAction(self.actionRASXSUpdateInsertMeasuredPoints)
        self.menuStreamCenterlineAttributes.addAction(self.actionRASTopology1D)
        self.menuStreamCenterlineAttributes.addAction(self.actionRASLengthsStations)
        self.menuStreamCenterlineAttributes.addSeparator()
        self.menuStreamCenterlineAttributes.addAction(self.actionRASStreamCenterlineAll)
        self.menuStreamCenterlineAttributes.addSeparator()
        self.menuStreamCenterlineAttributes.addAction(self.actionCopyStreamCenterlines2Flowpaths)
        self.menuBridges_Culverts.addAction(self.actionRASBRRiverReachNames)
        self.menuBridges_Culverts.addAction(self.actionRASBRStationing)
        self.menuBridges_Culverts.addSeparator()
        self.menuBridges_Culverts.addAction(self.actionRASBRElevations)
        self.menuBridges_Culverts.addSeparator()
        self.menuBridges_Culverts.addAction(self.actionRASBRAll)
        self.menuInline_Structures.addAction(self.actionRASInlRiverReachNames)
        self.menuInline_Structures.addAction(self.actionRASInlStationing)
        self.menuInline_Structures.addSeparator()
        self.menuInline_Structures.addAction(self.actionRASInlElevations)
        self.menuInline_Structures.addSeparator()
        self.menuInline_Structures.addAction(self.actionRASInlAll)
        self.menuLateral_Structures.addAction(self.actionRASLatRiverReachNames)
        self.menuLateral_Structures.addAction(self.actionRASLatStationing)
        self.menuLateral_Structures.addSeparator()
        self.menuLateral_Structures.addAction(self.actionRASLatElevations)
        self.menuLateral_Structures.addSeparator()
        self.menuLateral_Structures.addAction(self.actionRASLatAll)
        self.menuStorage_Areas.addAction(self.actionRASSATerrainPointExtraction)
        self.menuStorage_Areas.addAction(self.actionRASSAElevationVolumeData)
        self.menuStorage_Areas.addSeparator()
        self.menuStorage_Areas.addAction(self.actionRASSAAll)
        self.menuStorage_Areas_Connections.addAction(self.actionRASSacAssignNearestSA)
        self.menuStorage_Areas_Connections.addAction(self.actionRASSacElevations)
        self.menuStorage_Areas_Connections.addSeparator()
        self.menuStorage_Areas_Connections.addAction(self.actionRASSacAll)
        self.menu_Geometry.addAction(self.menuStreamCenterlineAttributes.menuAction())
        self.menu_Geometry.addAction(self.menuXS_Cut_Line_Attributes.menuAction())
        self.menu_Geometry.addAction(self.actionRASManningsNValues)
        self.menu_Geometry.addAction(self.actionRASLevees)
        self.menu_Geometry.addAction(self.actionRASIneffectiveFlowAreas)
        self.menu_Geometry.addAction(self.actionRASBlockedObstructions)
        self.menu_Geometry.addSeparator()
        self.menu_Geometry.addAction(self.menuBridges_Culverts.menuAction())
        self.menu_Geometry.addAction(self.menuInline_Structures.menuAction())
        self.menu_Geometry.addAction(self.menuLateral_Structures.menuAction())
        self.menu_Geometry.addAction(self.menuStorage_Areas.menuAction())
        self.menu_Geometry.addAction(self.menuStorage_Areas_Connections.menuAction())
        self.menu_Geometry.addSeparator()
        self.menu_Geometry.addAction(self.actionRASCreateRASGISImport)
        self.menu_Geometry.addSeparator()
        self.menu_Geometry.addAction(self.actionRASCreate2dAreaPoints)
        self.menu_Geometry.addAction(self.actionRASPreview2DMesh)
        self.menu_Geometry.addAction(self.actionRASSave2DPointsToHECRASGeometry)
        self.menuDB.addAction(self.actionRefreshConnections)
        self.menuDB.addAction(self.actionCreateNewSchema)
        self.menuDB.addAction(self.actionRASCreateRdbTables)
        self.menuDB.addAction(self.actionRASImportLayersIntoRdbTables)
        self.menuDB.addAction(self.actionRASLoadRdbTablesIntoQGIS)
        self.menuSettings.addAction(self.actionOptions)
        self.menuSettings.addAction(self.actionRestoreDefaultOptions)
        self.menubar.addAction(self.menuDB.menuAction())
        self.menubar.addAction(self.menuSettings.menuAction())
        self.menubar.addAction(self.menu_Geometry.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())
        self.dbToolBar.addAction(self.actionRefreshConnections)
        self.dbToolBar.addAction(self.actionCreateNewSchema)
        self.dbToolBar.addAction(self.actionRASCreateRdbTables)
        self.dbToolBar.addAction(self.actionRASImportLayersIntoRdbTables)
        self.dbToolBar.addAction(self.actionRASLoadRdbTablesIntoQGIS)
        self.settingsToolBar.addAction(self.actionOptions)
        self.rasGeomToolBar.addAction(self.actionRASTopology1D)
        self.rasGeomToolBar.addAction(self.actionRASLengthsStations)
        self.rasGeomToolBar.addAction(self.actionRASStreamCenterlineAll)
        self.rasGeomToolBar.addAction(self.actionRASXSRiverReachNames)
        self.rasGeomToolBar.addAction(self.actionRASXSStationing)
        self.rasGeomToolBar.addAction(self.actionRASXSBankStations)
        self.rasGeomToolBar.addAction(self.actionRASXSDownstreamReachLengths)
        self.rasGeomToolBar.addAction(self.actionRASXSElevations)
        self.rasGeomToolBar.addAction(self.actionRASXSAll)
        self.rasImportExportToolBar.addAction(self.actionRASCreateRASGISImport)
        self.rasOptGeomToolBar.addAction(self.actionRASManningsNValues)
        self.rasOptGeomToolBar.addAction(self.actionRASLevees)
        self.rasOptGeomToolBar.addAction(self.actionRASIneffectiveFlowAreas)
        self.rasOptGeomToolBar.addAction(self.actionRASBlockedObstructions)
        self.rasOptGeomToolBar.addAction(self.actionRASXSUpdateInsertMeasuredPoints)
        self.rasStructuresToolBar.addAction(self.actionRASBRAll)
        self.rasStructuresToolBar.addAction(self.actionRASInlAll)
        self.rasStructuresToolBar.addAction(self.actionRASLatAll)
        self.rasStructuresToolBar.addAction(self.actionRASSAAll)
        self.rasStructuresToolBar.addAction(self.actionRASSacAll)
        self.rasSAToolBar.addAction(self.actionRASSATerrainPointExtraction)
        self.rasSAToolBar.addAction(self.actionRASSAElevationVolumeData)
        self.ras2dToolBar.addAction(self.actionRASCreate2dAreaPoints)
        self.ras2dToolBar.addAction(self.actionRASPreview2DMesh)
        self.ras2dToolBar.addAction(self.actionRASSave2DPointsToHECRASGeometry)

        self.retranslateUi(RiverGIS)
        QtCore.QMetaObject.connectSlotsByName(RiverGIS)

    def retranslateUi(self, RiverGIS):
        RiverGIS.setWindowTitle(_translate("RiverGIS", "RiverGIS", None))
        self.labelCurSchema.setText(_translate("RiverGIS", "Schema:", None))
        self.labelCurDatabase.setText(_translate("RiverGIS", "DB Connection:", None))
        self.label.setText(_translate("RiverGIS", "Projection", None))
        self.menuHelp.setTitle(_translate("RiverGIS", "Help", None))
        self.menu_Geometry.setTitle(_translate("RiverGIS", "RAS Geometry", None))
        self.menuXS_Cut_Line_Attributes.setTitle(_translate("RiverGIS", "XS Cut Line Attributes", None))
        self.menuStreamCenterlineAttributes.setTitle(_translate("RiverGIS", "Stream Centerline Attributes", None))
        self.menuBridges_Culverts.setTitle(_translate("RiverGIS", "Bridges/Culverts", None))
        self.menuInline_Structures.setTitle(_translate("RiverGIS", "Inline Structures", None))
        self.menuLateral_Structures.setTitle(_translate("RiverGIS", "Lateral Structures", None))
        self.menuStorage_Areas.setTitle(_translate("RiverGIS", "Storage Areas", None))
        self.menuStorage_Areas_Connections.setTitle(_translate("RiverGIS", "Storage Area Connections", None))
        self.menuDB.setTitle(_translate("RiverGIS", "Database", None))
        self.menuSettings.setTitle(_translate("RiverGIS", "Settings", None))
        self.dbToolBar.setWindowTitle(_translate("RiverGIS", "toolBar", None))
        self.settingsToolBar.setWindowTitle(_translate("RiverGIS", "toolBar", None))
        self.rasGeomToolBar.setWindowTitle(_translate("RiverGIS", "toolBar", None))
        self.rasImportExportToolBar.setWindowTitle(_translate("RiverGIS", "toolBar", None))
        self.rasOptGeomToolBar.setWindowTitle(_translate("RiverGIS", "toolBar", None))
        self.rasStructuresToolBar.setWindowTitle(_translate("RiverGIS", "toolBar", None))
        self.rasSAToolBar.setWindowTitle(_translate("RiverGIS", "toolBar", None))
        self.ras2dToolBar.setWindowTitle(_translate("RiverGIS", "toolBar", None))
        self.actionRASCreate2dAreaPoints.setText(_translate("RiverGIS", "Create 2D Computational Points", None))
        self.actionHelpContents.setText(_translate("RiverGIS", "Contents", None))
        self.actionRASWaterSurfaceGeneration.setText(_translate("RiverGIS", "Water Surface Generation", None))
        self.actionRefreshConnections.setText(_translate("RiverGIS", "Refresh Connections List", None))
        self.actionRASSave2DPointsToHECRASGeometry.setText(_translate("RiverGIS", "Save 2D Points to HEC-RAS Geometry", None))
        self.actionRASPreview2DMesh.setText(_translate("RiverGIS", "Preview 2D Mesh", None))
        self.actionRASCreateRdbTables.setText(_translate("RiverGIS", "Create River Database Tables", None))
        self.actionRASCreateRdbTables.setToolTip(_translate("RiverGIS", "RAS 1D Create River Database Tables", None))
        self.actionRASManningsNValues.setText(_translate("RiverGIS", "Extract Manning\'s n Values", None))
        self.actionRASManningsNValues.setToolTip(_translate("RiverGIS", "RAS 1D Extract Manning\'s n Values", None))
        self.actionRASCreateRASGISImport.setText(_translate("RiverGIS", "Create RAS GIS Import File", None))
        self.actionRASTopology1D.setText(_translate("RiverGIS", "Topology", None))
        self.actionRASTopology1D.setToolTip(_translate("RiverGIS", "RAS 1D Stream Centerlines Topology", None))
        self.actionRASLengthsStations.setText(_translate("RiverGIS", "Lengths/Stations", None))
        self.actionRASLengthsStations.setToolTip(_translate("RiverGIS", "RAS 1D Stream Centerlines Lengths/Stations", None))
        self.actionRASStreamCenterlineAll.setText(_translate("RiverGIS", "All", None))
        self.actionRASStreamCenterlineAll.setToolTip(_translate("RiverGIS", "RAS 1D Stream Centerlines All", None))
        self.actionRASXSRiverReachNames.setText(_translate("RiverGIS", "River/Reach Names", None))
        self.actionRASXSRiverReachNames.setToolTip(_translate("RiverGIS", "RAS 1D Cross-sections River/Reach Names", None))
        self.actionRASXSStationing.setText(_translate("RiverGIS", "Stationing", None))
        self.actionRASXSStationing.setToolTip(_translate("RiverGIS", "RAS 1D Cross-sections Stationing", None))
        self.actionRASXSBankStations.setText(_translate("RiverGIS", "Bank Stations", None))
        self.actionRASXSBankStations.setToolTip(_translate("RiverGIS", "RAS 1D Cross-sections Bank Stations", None))
        self.actionRASXSDownstreamReachLengths.setText(_translate("RiverGIS", "Downstream Reach Lengths", None))
        self.actionRASXSDownstreamReachLengths.setToolTip(_translate("RiverGIS", "RAS 1D Cross-sections Downstream Reach Lengths", None))
        self.actionRASXSElevations.setText(_translate("RiverGIS", "Elevations", None))
        self.actionRASXSElevations.setToolTip(_translate("RiverGIS", "RAS 1D Cross-sections Elevations", None))
        self.actionRASXSAll.setText(_translate("RiverGIS", "All", None))
        self.actionRASXSAll.setToolTip(_translate("RiverGIS", "RAS 1D Cross-sections All", None))
        self.actionRASImportLayersIntoRdbTables.setText(_translate("RiverGIS", "Import Layers Into River Database Tables", None))
        self.actionRASImportLayersIntoRdbTables.setToolTip(_translate("RiverGIS", "RAS 1D Import Layers Into River Database Tables", None))
        self.actionRASLevees.setText(_translate("RiverGIS", "Levees", None))
        self.actionRASLevees.setToolTip(_translate("RiverGIS", "RAS 1D Levees", None))
        self.actionRASIneffectiveFlowAreas.setText(_translate("RiverGIS", "Ineffective Flow Areas", None))
        self.actionRASIneffectiveFlowAreas.setToolTip(_translate("RiverGIS", "RAS 1D Ineffective Flow Areas", None))
        self.actionRASBlockedObstructions.setText(_translate("RiverGIS", "Blocked Obstructions", None))
        self.actionRASBlockedObstructions.setToolTip(_translate("RiverGIS", "RAS 1D Blocked Obstructions", None))
        self.actionRASLoadRdbTablesIntoQGIS.setText(_translate("RiverGIS", "Load River Database Tables Into QGIS", None))
        self.actionRASLoadRdbTablesIntoQGIS.setToolTip(_translate("RiverGIS", "RAS 1D Load River Database Tables Into QGIS", None))
        self.actionOptions.setText(_translate("RiverGIS", "Options", None))
        self.actionDebugMode.setText(_translate("RiverGIS", "Debug mode", None))
        self.actionCopyStreamCenterlines2Flowpaths.setText(_translate("RiverGIS", "Copy Stream Centerlines to Flowpaths", None))
        self.actionAlwaysOnTop.setText(_translate("RiverGIS", "Always on top", None))
        self.actionRASXSUpdateInsertMeasuredPoints.setText(_translate("RiverGIS", "Update - Insert Measured Points", None))
        self.actionRASBRRiverReachNames.setText(_translate("RiverGIS", "River/Reach Names", None))
        self.actionRASBRRiverReachNames.setToolTip(_translate("RiverGIS", "Bridges/Culverts River Reach Names", None))
        self.actionRASBRStationing.setText(_translate("RiverGIS", "Stationing", None))
        self.actionRASBRStationing.setToolTip(_translate("RiverGIS", "Bridges/Culverts Stationing", None))
        self.actionRASBRElevations.setText(_translate("RiverGIS", "Elevations", None))
        self.actionRASBRElevations.setToolTip(_translate("RiverGIS", "Bridges/Culverts Elevations", None))
        self.actionRASBRAll.setText(_translate("RiverGIS", "All", None))
        self.actionRASBRAll.setToolTip(_translate("RiverGIS", "RAS 1D Bridges/Culverts - All", None))
        self.actionRASInlRiverReachNames.setText(_translate("RiverGIS", "River/Reach Names", None))
        self.actionRASInlRiverReachNames.setToolTip(_translate("RiverGIS", "RAS 1D Inline Structures River/Reach Names", None))
        self.actionRASInlStationing.setText(_translate("RiverGIS", "Stationing", None))
        self.actionRASInlStationing.setToolTip(_translate("RiverGIS", "RAS 1D Inline Structures Stationing", None))
        self.actionRASInlElevations.setText(_translate("RiverGIS", "Elevations", None))
        self.actionRASInlElevations.setToolTip(_translate("RiverGIS", "RAS 1D Inline Structures Elevations", None))
        self.actionRASInlAll.setText(_translate("RiverGIS", "All", None))
        self.actionRASInlAll.setToolTip(_translate("RiverGIS", "RAS 1D Inline Structures - All", None))
        self.actionRASLatRiverReachNames.setText(_translate("RiverGIS", "River/Reach Names", None))
        self.actionRASLatRiverReachNames.setToolTip(_translate("RiverGIS", "RAS 1D Lateral Structures River/Reach Names", None))
        self.actionRASLatStationing.setText(_translate("RiverGIS", "Stationing", None))
        self.actionRASLatStationing.setToolTip(_translate("RiverGIS", "RAS 1D Lateral Structures Stationing", None))
        self.actionRASLatElevations.setText(_translate("RiverGIS", "Elevations", None))
        self.actionRASLatElevations.setToolTip(_translate("RiverGIS", "RAS 1D Lateral Structures Elevations", None))
        self.actionRASLatAll.setText(_translate("RiverGIS", "All", None))
        self.actionRASLatAll.setToolTip(_translate("RiverGIS", "RAS 1D Lateral Structures - All", None))
        self.actionRASSAElevationVolumeData.setText(_translate("RiverGIS", "Elevation-Volume Data", None))
        self.actionRASSAElevationVolumeData.setIconText(_translate("RiverGIS", "SA Elevation-Volume Data", None))
        self.actionRASSAElevationVolumeData.setToolTip(_translate("RiverGIS", "RAS 1D SA Elevation-Volume Data", None))
        self.actionRASSATerrainPointExtraction.setText(_translate("RiverGIS", "Terrain Point Extraction", None))
        self.actionRASSATerrainPointExtraction.setIconText(_translate("RiverGIS", "SA Terrain Point Extraction", None))
        self.actionRASSATerrainPointExtraction.setToolTip(_translate("RiverGIS", "RAS 1D SA Terrain Point Extraction", None))
        self.actionRASSAAll.setText(_translate("RiverGIS", "All", None))
        self.actionRASSAAll.setToolTip(_translate("RiverGIS", "RAS 1D Storage Areas - All", None))
        self.actionRASSacAssignNearestSA.setText(_translate("RiverGIS", "Assign Nearest SA", None))
        self.actionRASSacAssignNearestSA.setToolTip(_translate("RiverGIS", "RAS 1D SA Conn Assign Nearest SA", None))
        self.actionRASSacElevations.setText(_translate("RiverGIS", "Elevations", None))
        self.actionRASSacElevations.setToolTip(_translate("RiverGIS", "RAS 1D SA Conn - Elevations", None))
        self.actionRASSacAll.setText(_translate("RiverGIS", "All", None))
        self.actionRASSacAll.setToolTip(_translate("RiverGIS", "RAS 1D SA Connections - All", None))
        self.actionWebsite.setText(_translate("RiverGIS", "Web site", None))
        self.actionAbout.setText(_translate("RiverGIS", "About", None))
        self.actionRestoreDefaultOptions.setText(_translate("RiverGIS", "Restore Default Options", None))
        self.actionCreateNewSchema.setText(_translate("RiverGIS", "Create new schema", None))

