# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/ui_importDataIntoRasTables.ui'
#
# Created: Thu Dec 03 10:27:39 2015
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_importDataIntoRasTables(object):
    def setupUi(self, importDataIntoRasTables):
        importDataIntoRasTables.setObjectName(_fromUtf8("importDataIntoRasTables"))
        importDataIntoRasTables.resize(362, 648)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(importDataIntoRasTables.sizePolicy().hasHeightForWidth())
        importDataIntoRasTables.setSizePolicy(sizePolicy)
        self.gridLayout = QtGui.QGridLayout(importDataIntoRasTables)
        self.gridLayout.setMargin(3)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.tabWidget = QtGui.QTabWidget(importDataIntoRasTables)
        self.tabWidget.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.general = QtGui.QWidget()
        self.general.setObjectName(_fromUtf8("general"))
        self.gridLayout_2 = QtGui.QGridLayout(self.general)
        self.gridLayout_2.setMargin(6)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.label = QtGui.QLabel(self.general)
        self.label.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout.addWidget(self.label)
        self.cboStreamCenterlines = QtGui.QComboBox(self.general)
        self.cboStreamCenterlines.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.cboStreamCenterlines.setObjectName(_fromUtf8("cboStreamCenterlines"))
        self.verticalLayout.addWidget(self.cboStreamCenterlines)
        self.horizontalLayout_30 = QtGui.QHBoxLayout()
        self.horizontalLayout_30.setObjectName(_fromUtf8("horizontalLayout_30"))
        self.label_35 = QtGui.QLabel(self.general)
        self.label_35.setObjectName(_fromUtf8("label_35"))
        self.horizontalLayout_30.addWidget(self.label_35)
        self.cboRiverNameAttr = QtGui.QComboBox(self.general)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cboRiverNameAttr.sizePolicy().hasHeightForWidth())
        self.cboRiverNameAttr.setSizePolicy(sizePolicy)
        self.cboRiverNameAttr.setObjectName(_fromUtf8("cboRiverNameAttr"))
        self.horizontalLayout_30.addWidget(self.cboRiverNameAttr)
        self.verticalLayout.addLayout(self.horizontalLayout_30)
        self.horizontalLayout_31 = QtGui.QHBoxLayout()
        self.horizontalLayout_31.setContentsMargins(-1, 0, -1, 0)
        self.horizontalLayout_31.setObjectName(_fromUtf8("horizontalLayout_31"))
        self.label_36 = QtGui.QLabel(self.general)
        self.label_36.setObjectName(_fromUtf8("label_36"))
        self.horizontalLayout_31.addWidget(self.label_36)
        self.cboReachNameAttr = QtGui.QComboBox(self.general)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cboReachNameAttr.sizePolicy().hasHeightForWidth())
        self.cboReachNameAttr.setSizePolicy(sizePolicy)
        self.cboReachNameAttr.setObjectName(_fromUtf8("cboReachNameAttr"))
        self.horizontalLayout_31.addWidget(self.cboReachNameAttr)
        self.verticalLayout.addLayout(self.horizontalLayout_31)
        self.label_2 = QtGui.QLabel(self.general)
        self.label_2.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.verticalLayout.addWidget(self.label_2)
        self.cboXsecs = QtGui.QComboBox(self.general)
        self.cboXsecs.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.cboXsecs.setObjectName(_fromUtf8("cboXsecs"))
        self.verticalLayout.addWidget(self.cboXsecs)
        self.label_4 = QtGui.QLabel(self.general)
        self.label_4.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.verticalLayout.addWidget(self.label_4)
        self.cboBanks = QtGui.QComboBox(self.general)
        self.cboBanks.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.cboBanks.setObjectName(_fromUtf8("cboBanks"))
        self.verticalLayout.addWidget(self.cboBanks)
        self.label_7 = QtGui.QLabel(self.general)
        self.label_7.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.verticalLayout.addWidget(self.label_7)
        self.cboFlowPaths = QtGui.QComboBox(self.general)
        self.cboFlowPaths.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.cboFlowPaths.setObjectName(_fromUtf8("cboFlowPaths"))
        self.verticalLayout.addWidget(self.cboFlowPaths)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label_8 = QtGui.QLabel(self.general)
        self.label_8.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.horizontalLayout.addWidget(self.label_8)
        self.cboFlowpathType = QtGui.QComboBox(self.general)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cboFlowpathType.sizePolicy().hasHeightForWidth())
        self.cboFlowpathType.setSizePolicy(sizePolicy)
        self.cboFlowpathType.setMinimumSize(QtCore.QSize(0, 0))
        self.cboFlowpathType.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.cboFlowpathType.setObjectName(_fromUtf8("cboFlowpathType"))
        self.horizontalLayout.addWidget(self.cboFlowpathType)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.label_3 = QtGui.QLabel(self.general)
        self.label_3.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.verticalLayout.addWidget(self.label_3)
        self.cboLevees = QtGui.QComboBox(self.general)
        self.cboLevees.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.cboLevees.setObjectName(_fromUtf8("cboLevees"))
        self.verticalLayout.addWidget(self.cboLevees)
        self.label_5 = QtGui.QLabel(self.general)
        self.label_5.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.verticalLayout.addWidget(self.label_5)
        self.cboIneffective = QtGui.QComboBox(self.general)
        self.cboIneffective.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.cboIneffective.setObjectName(_fromUtf8("cboIneffective"))
        self.verticalLayout.addWidget(self.cboIneffective)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label_10 = QtGui.QLabel(self.general)
        self.label_10.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.horizontalLayout_3.addWidget(self.label_10)
        self.cboIneffElev = QtGui.QComboBox(self.general)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cboIneffElev.sizePolicy().hasHeightForWidth())
        self.cboIneffElev.setSizePolicy(sizePolicy)
        self.cboIneffElev.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.cboIneffElev.setObjectName(_fromUtf8("cboIneffElev"))
        self.horizontalLayout_3.addWidget(self.cboIneffElev)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.label_6 = QtGui.QLabel(self.general)
        self.label_6.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.verticalLayout.addWidget(self.label_6)
        self.cboObstructions = QtGui.QComboBox(self.general)
        self.cboObstructions.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.cboObstructions.setObjectName(_fromUtf8("cboObstructions"))
        self.verticalLayout.addWidget(self.cboObstructions)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label_11 = QtGui.QLabel(self.general)
        self.label_11.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.horizontalLayout_4.addWidget(self.label_11)
        self.cboObstructionsElev = QtGui.QComboBox(self.general)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cboObstructionsElev.sizePolicy().hasHeightForWidth())
        self.cboObstructionsElev.setSizePolicy(sizePolicy)
        self.cboObstructionsElev.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.cboObstructionsElev.setObjectName(_fromUtf8("cboObstructionsElev"))
        self.horizontalLayout_4.addWidget(self.cboObstructionsElev)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.label_12 = QtGui.QLabel(self.general)
        self.label_12.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.verticalLayout.addWidget(self.label_12)
        self.cboLanduse = QtGui.QComboBox(self.general)
        self.cboLanduse.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.cboLanduse.setObjectName(_fromUtf8("cboLanduse"))
        self.verticalLayout.addWidget(self.cboLanduse)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.label_13 = QtGui.QLabel(self.general)
        self.label_13.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.horizontalLayout_5.addWidget(self.label_13)
        self.cboLandCodeAttr = QtGui.QComboBox(self.general)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cboLandCodeAttr.sizePolicy().hasHeightForWidth())
        self.cboLandCodeAttr.setSizePolicy(sizePolicy)
        self.cboLandCodeAttr.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.cboLandCodeAttr.setObjectName(_fromUtf8("cboLandCodeAttr"))
        self.horizontalLayout_5.addWidget(self.cboLandCodeAttr)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.label_14 = QtGui.QLabel(self.general)
        self.label_14.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.horizontalLayout_6.addWidget(self.label_14)
        self.cboManningAttr = QtGui.QComboBox(self.general)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cboManningAttr.sizePolicy().hasHeightForWidth())
        self.cboManningAttr.setSizePolicy(sizePolicy)
        self.cboManningAttr.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.cboManningAttr.setObjectName(_fromUtf8("cboManningAttr"))
        self.horizontalLayout_6.addWidget(self.cboManningAttr)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.gridLayout_2.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.tabWidget.addTab(self.general, _fromUtf8(""))
        self.flowAreas = QtGui.QWidget()
        self.flowAreas.setObjectName(_fromUtf8("flowAreas"))
        self.gridLayout_7 = QtGui.QGridLayout(self.flowAreas)
        self.gridLayout_7.setMargin(6)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setContentsMargins(-1, 0, -1, -1)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.groupBox = QtGui.QGroupBox(self.flowAreas)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.gridLayout_4 = QtGui.QGridLayout(self.groupBox)
        self.gridLayout_4.setMargin(3)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.label_9 = QtGui.QLabel(self.groupBox)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.horizontalLayout_7.addWidget(self.label_9)
        self.cbo2dFlowAreas = QtGui.QComboBox(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cbo2dFlowAreas.sizePolicy().hasHeightForWidth())
        self.cbo2dFlowAreas.setSizePolicy(sizePolicy)
        self.cbo2dFlowAreas.setMinimumSize(QtCore.QSize(0, 0))
        self.cbo2dFlowAreas.setAcceptDrops(False)
        self.cbo2dFlowAreas.setMinimumContentsLength(0)
        self.cbo2dFlowAreas.setFrame(True)
        self.cbo2dFlowAreas.setObjectName(_fromUtf8("cbo2dFlowAreas"))
        self.horizontalLayout_7.addWidget(self.cbo2dFlowAreas)
        self.verticalLayout_4.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.AreaNameAttributeLabel = QtGui.QLabel(self.groupBox)
        self.AreaNameAttributeLabel.setObjectName(_fromUtf8("AreaNameAttributeLabel"))
        self.horizontalLayout_8.addWidget(self.AreaNameAttributeLabel)
        self.cbo2dAreasNameAttr = QtGui.QComboBox(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cbo2dAreasNameAttr.sizePolicy().hasHeightForWidth())
        self.cbo2dAreasNameAttr.setSizePolicy(sizePolicy)
        self.cbo2dAreasNameAttr.setObjectName(_fromUtf8("cbo2dAreasNameAttr"))
        self.horizontalLayout_8.addWidget(self.cbo2dAreasNameAttr)
        self.verticalLayout_4.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setSpacing(6)
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.AreaNameAttributeLabel_2 = QtGui.QLabel(self.groupBox)
        self.AreaNameAttributeLabel_2.setObjectName(_fromUtf8("AreaNameAttributeLabel_2"))
        self.horizontalLayout_9.addWidget(self.AreaNameAttributeLabel_2)
        self.cbo2dAreasMeshSizeAttr = QtGui.QComboBox(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cbo2dAreasMeshSizeAttr.sizePolicy().hasHeightForWidth())
        self.cbo2dAreasMeshSizeAttr.setSizePolicy(sizePolicy)
        self.cbo2dAreasMeshSizeAttr.setObjectName(_fromUtf8("cbo2dAreasMeshSizeAttr"))
        self.horizontalLayout_9.addWidget(self.cbo2dAreasMeshSizeAttr)
        self.verticalLayout_4.addLayout(self.horizontalLayout_9)
        self.gridLayout_4.addLayout(self.verticalLayout_4, 0, 0, 1, 1)
        self.verticalLayout_3.addWidget(self.groupBox)
        self.groupBox_2 = QtGui.QGroupBox(self.flowAreas)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.gridLayout_5 = QtGui.QGridLayout(self.groupBox_2)
        self.gridLayout_5.setMargin(3)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.AreaNameAttributeLabel_3 = QtGui.QLabel(self.groupBox_2)
        self.AreaNameAttributeLabel_3.setObjectName(_fromUtf8("AreaNameAttributeLabel_3"))
        self.horizontalLayout_10.addWidget(self.AreaNameAttributeLabel_3)
        self.cboBreaklines = QtGui.QComboBox(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cboBreaklines.sizePolicy().hasHeightForWidth())
        self.cboBreaklines.setSizePolicy(sizePolicy)
        self.cboBreaklines.setObjectName(_fromUtf8("cboBreaklines"))
        self.horizontalLayout_10.addWidget(self.cboBreaklines)
        self.verticalLayout_5.addLayout(self.horizontalLayout_10)
        self.label_15 = QtGui.QLabel(self.groupBox_2)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.verticalLayout_5.addWidget(self.label_15)
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        self.AreaNameAttributeLabel_4 = QtGui.QLabel(self.groupBox_2)
        self.AreaNameAttributeLabel_4.setObjectName(_fromUtf8("AreaNameAttributeLabel_4"))
        self.horizontalLayout_11.addWidget(self.AreaNameAttributeLabel_4)
        self.cboBreaklineCellSizeAlongAttr = QtGui.QComboBox(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cboBreaklineCellSizeAlongAttr.sizePolicy().hasHeightForWidth())
        self.cboBreaklineCellSizeAlongAttr.setSizePolicy(sizePolicy)
        self.cboBreaklineCellSizeAlongAttr.setObjectName(_fromUtf8("cboBreaklineCellSizeAlongAttr"))
        self.horizontalLayout_11.addWidget(self.cboBreaklineCellSizeAlongAttr)
        self.verticalLayout_5.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_12 = QtGui.QHBoxLayout()
        self.horizontalLayout_12.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_12.setObjectName(_fromUtf8("horizontalLayout_12"))
        self.label_16 = QtGui.QLabel(self.groupBox_2)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.horizontalLayout_12.addWidget(self.label_16)
        self.cboBreaklineCellSizeAcrossAttr = QtGui.QComboBox(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cboBreaklineCellSizeAcrossAttr.sizePolicy().hasHeightForWidth())
        self.cboBreaklineCellSizeAcrossAttr.setSizePolicy(sizePolicy)
        self.cboBreaklineCellSizeAcrossAttr.setObjectName(_fromUtf8("cboBreaklineCellSizeAcrossAttr"))
        self.horizontalLayout_12.addWidget(self.cboBreaklineCellSizeAcrossAttr)
        self.verticalLayout_5.addLayout(self.horizontalLayout_12)
        self.horizontalLayout_13 = QtGui.QHBoxLayout()
        self.horizontalLayout_13.setObjectName(_fromUtf8("horizontalLayout_13"))
        self.label_17 = QtGui.QLabel(self.groupBox_2)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.horizontalLayout_13.addWidget(self.label_17)
        self.cboBreaklineCellRowsAttr = QtGui.QComboBox(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cboBreaklineCellRowsAttr.sizePolicy().hasHeightForWidth())
        self.cboBreaklineCellRowsAttr.setSizePolicy(sizePolicy)
        self.cboBreaklineCellRowsAttr.setObjectName(_fromUtf8("cboBreaklineCellRowsAttr"))
        self.horizontalLayout_13.addWidget(self.cboBreaklineCellRowsAttr)
        self.verticalLayout_5.addLayout(self.horizontalLayout_13)
        self.gridLayout_5.addLayout(self.verticalLayout_5, 0, 0, 1, 1)
        self.verticalLayout_3.addWidget(self.groupBox_2)
        self.groupBox_3 = QtGui.QGroupBox(self.flowAreas)
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.gridLayout_6 = QtGui.QGridLayout(self.groupBox_3)
        self.gridLayout_6.setMargin(3)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.verticalLayout_6 = QtGui.QVBoxLayout()
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.horizontalLayout_14 = QtGui.QHBoxLayout()
        self.horizontalLayout_14.setObjectName(_fromUtf8("horizontalLayout_14"))
        self.label_18 = QtGui.QLabel(self.groupBox_3)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.horizontalLayout_14.addWidget(self.label_18)
        self.cboBreakpoints = QtGui.QComboBox(self.groupBox_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cboBreakpoints.sizePolicy().hasHeightForWidth())
        self.cboBreakpoints.setSizePolicy(sizePolicy)
        self.cboBreakpoints.setObjectName(_fromUtf8("cboBreakpoints"))
        self.horizontalLayout_14.addWidget(self.cboBreakpoints)
        self.verticalLayout_6.addLayout(self.horizontalLayout_14)
        self.gridLayout_6.addLayout(self.verticalLayout_6, 0, 0, 1, 1)
        self.verticalLayout_3.addWidget(self.groupBox_3)
        self.gridLayout_7.addLayout(self.verticalLayout_3, 0, 0, 1, 1)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_7.addItem(spacerItem, 1, 0, 1, 1)
        self.tabWidget.addTab(self.flowAreas, _fromUtf8(""))
        self.structures = QtGui.QWidget()
        self.structures.setObjectName(_fromUtf8("structures"))
        self.gridLayout_3 = QtGui.QGridLayout(self.structures)
        self.gridLayout_3.setMargin(6)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.groupBox_4 = QtGui.QGroupBox(self.structures)
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.gridLayout_8 = QtGui.QGridLayout(self.groupBox_4)
        self.gridLayout_8.setMargin(3)
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        self.verticalLayout_7 = QtGui.QVBoxLayout()
        self.verticalLayout_7.setContentsMargins(-1, 0, -1, 0)
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label_19 = QtGui.QLabel(self.groupBox_4)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.horizontalLayout_2.addWidget(self.label_19)
        self.cboBridgesLayer = QtGui.QComboBox(self.groupBox_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cboBridgesLayer.sizePolicy().hasHeightForWidth())
        self.cboBridgesLayer.setSizePolicy(sizePolicy)
        self.cboBridgesLayer.setObjectName(_fromUtf8("cboBridgesLayer"))
        self.horizontalLayout_2.addWidget(self.cboBridgesLayer)
        self.verticalLayout_7.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_15 = QtGui.QHBoxLayout()
        self.horizontalLayout_15.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_15.setObjectName(_fromUtf8("horizontalLayout_15"))
        self.label_20 = QtGui.QLabel(self.groupBox_4)
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.horizontalLayout_15.addWidget(self.label_20)
        self.cboBridgesName = QtGui.QComboBox(self.groupBox_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cboBridgesName.sizePolicy().hasHeightForWidth())
        self.cboBridgesName.setSizePolicy(sizePolicy)
        self.cboBridgesName.setObjectName(_fromUtf8("cboBridgesName"))
        self.horizontalLayout_15.addWidget(self.cboBridgesName)
        self.verticalLayout_7.addLayout(self.horizontalLayout_15)
        self.horizontalLayout_16 = QtGui.QHBoxLayout()
        self.horizontalLayout_16.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_16.setObjectName(_fromUtf8("horizontalLayout_16"))
        self.label_21 = QtGui.QLabel(self.groupBox_4)
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.horizontalLayout_16.addWidget(self.label_21)
        self.cboBridgesUsDist = QtGui.QComboBox(self.groupBox_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cboBridgesUsDist.sizePolicy().hasHeightForWidth())
        self.cboBridgesUsDist.setSizePolicy(sizePolicy)
        self.cboBridgesUsDist.setObjectName(_fromUtf8("cboBridgesUsDist"))
        self.horizontalLayout_16.addWidget(self.cboBridgesUsDist)
        self.verticalLayout_7.addLayout(self.horizontalLayout_16)
        self.horizontalLayout_17 = QtGui.QHBoxLayout()
        self.horizontalLayout_17.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_17.setObjectName(_fromUtf8("horizontalLayout_17"))
        self.label_22 = QtGui.QLabel(self.groupBox_4)
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.horizontalLayout_17.addWidget(self.label_22)
        self.cboBridgesTopWidth = QtGui.QComboBox(self.groupBox_4)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cboBridgesTopWidth.sizePolicy().hasHeightForWidth())
        self.cboBridgesTopWidth.setSizePolicy(sizePolicy)
        self.cboBridgesTopWidth.setObjectName(_fromUtf8("cboBridgesTopWidth"))
        self.horizontalLayout_17.addWidget(self.cboBridgesTopWidth)
        self.verticalLayout_7.addLayout(self.horizontalLayout_17)
        self.gridLayout_8.addLayout(self.verticalLayout_7, 0, 0, 1, 1)
        self.verticalLayout_2.addWidget(self.groupBox_4)
        self.gridLayout_3.addLayout(self.verticalLayout_2, 0, 0, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem1, 3, 0, 1, 1)
        self.groupBox_5 = QtGui.QGroupBox(self.structures)
        self.groupBox_5.setObjectName(_fromUtf8("groupBox_5"))
        self.gridLayout_9 = QtGui.QGridLayout(self.groupBox_5)
        self.gridLayout_9.setMargin(3)
        self.gridLayout_9.setObjectName(_fromUtf8("gridLayout_9"))
        self.verticalLayout_8 = QtGui.QVBoxLayout()
        self.verticalLayout_8.setContentsMargins(-1, -1, -1, 0)
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.horizontalLayout_18 = QtGui.QHBoxLayout()
        self.horizontalLayout_18.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_18.setObjectName(_fromUtf8("horizontalLayout_18"))
        self.label_23 = QtGui.QLabel(self.groupBox_5)
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.horizontalLayout_18.addWidget(self.label_23)
        self.cboInlineStrLayer = QtGui.QComboBox(self.groupBox_5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cboInlineStrLayer.sizePolicy().hasHeightForWidth())
        self.cboInlineStrLayer.setSizePolicy(sizePolicy)
        self.cboInlineStrLayer.setObjectName(_fromUtf8("cboInlineStrLayer"))
        self.horizontalLayout_18.addWidget(self.cboInlineStrLayer)
        self.verticalLayout_8.addLayout(self.horizontalLayout_18)
        self.horizontalLayout_19 = QtGui.QHBoxLayout()
        self.horizontalLayout_19.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_19.setObjectName(_fromUtf8("horizontalLayout_19"))
        self.label_24 = QtGui.QLabel(self.groupBox_5)
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.horizontalLayout_19.addWidget(self.label_24)
        self.cboInlineStrName = QtGui.QComboBox(self.groupBox_5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cboInlineStrName.sizePolicy().hasHeightForWidth())
        self.cboInlineStrName.setSizePolicy(sizePolicy)
        self.cboInlineStrName.setObjectName(_fromUtf8("cboInlineStrName"))
        self.horizontalLayout_19.addWidget(self.cboInlineStrName)
        self.verticalLayout_8.addLayout(self.horizontalLayout_19)
        self.horizontalLayout_20 = QtGui.QHBoxLayout()
        self.horizontalLayout_20.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_20.setObjectName(_fromUtf8("horizontalLayout_20"))
        self.label_25 = QtGui.QLabel(self.groupBox_5)
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.horizontalLayout_20.addWidget(self.label_25)
        self.cboInlineStrUsDist = QtGui.QComboBox(self.groupBox_5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cboInlineStrUsDist.sizePolicy().hasHeightForWidth())
        self.cboInlineStrUsDist.setSizePolicy(sizePolicy)
        self.cboInlineStrUsDist.setObjectName(_fromUtf8("cboInlineStrUsDist"))
        self.horizontalLayout_20.addWidget(self.cboInlineStrUsDist)
        self.verticalLayout_8.addLayout(self.horizontalLayout_20)
        self.horizontalLayout_21 = QtGui.QHBoxLayout()
        self.horizontalLayout_21.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_21.setObjectName(_fromUtf8("horizontalLayout_21"))
        self.label_26 = QtGui.QLabel(self.groupBox_5)
        self.label_26.setObjectName(_fromUtf8("label_26"))
        self.horizontalLayout_21.addWidget(self.label_26)
        self.cboInlineStrTopWidth = QtGui.QComboBox(self.groupBox_5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cboInlineStrTopWidth.sizePolicy().hasHeightForWidth())
        self.cboInlineStrTopWidth.setSizePolicy(sizePolicy)
        self.cboInlineStrTopWidth.setObjectName(_fromUtf8("cboInlineStrTopWidth"))
        self.horizontalLayout_21.addWidget(self.cboInlineStrTopWidth)
        self.verticalLayout_8.addLayout(self.horizontalLayout_21)
        self.gridLayout_9.addLayout(self.verticalLayout_8, 0, 0, 1, 1)
        self.gridLayout_3.addWidget(self.groupBox_5, 1, 0, 1, 1)
        self.groupBox_6 = QtGui.QGroupBox(self.structures)
        self.groupBox_6.setObjectName(_fromUtf8("groupBox_6"))
        self.gridLayout_10 = QtGui.QGridLayout(self.groupBox_6)
        self.gridLayout_10.setMargin(3)
        self.gridLayout_10.setObjectName(_fromUtf8("gridLayout_10"))
        self.verticalLayout_9 = QtGui.QVBoxLayout()
        self.verticalLayout_9.setContentsMargins(-1, -1, -1, 0)
        self.verticalLayout_9.setObjectName(_fromUtf8("verticalLayout_9"))
        self.horizontalLayout_22 = QtGui.QHBoxLayout()
        self.horizontalLayout_22.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_22.setObjectName(_fromUtf8("horizontalLayout_22"))
        self.label_27 = QtGui.QLabel(self.groupBox_6)
        self.label_27.setObjectName(_fromUtf8("label_27"))
        self.horizontalLayout_22.addWidget(self.label_27)
        self.cboLateralStrLayer = QtGui.QComboBox(self.groupBox_6)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cboLateralStrLayer.sizePolicy().hasHeightForWidth())
        self.cboLateralStrLayer.setSizePolicy(sizePolicy)
        self.cboLateralStrLayer.setObjectName(_fromUtf8("cboLateralStrLayer"))
        self.horizontalLayout_22.addWidget(self.cboLateralStrLayer)
        self.verticalLayout_9.addLayout(self.horizontalLayout_22)
        self.horizontalLayout_23 = QtGui.QHBoxLayout()
        self.horizontalLayout_23.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_23.setObjectName(_fromUtf8("horizontalLayout_23"))
        self.label_28 = QtGui.QLabel(self.groupBox_6)
        self.label_28.setObjectName(_fromUtf8("label_28"))
        self.horizontalLayout_23.addWidget(self.label_28)
        self.cboLateralStrName = QtGui.QComboBox(self.groupBox_6)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cboLateralStrName.sizePolicy().hasHeightForWidth())
        self.cboLateralStrName.setSizePolicy(sizePolicy)
        self.cboLateralStrName.setObjectName(_fromUtf8("cboLateralStrName"))
        self.horizontalLayout_23.addWidget(self.cboLateralStrName)
        self.verticalLayout_9.addLayout(self.horizontalLayout_23)
        self.horizontalLayout_24 = QtGui.QHBoxLayout()
        self.horizontalLayout_24.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_24.setObjectName(_fromUtf8("horizontalLayout_24"))
        self.label_29 = QtGui.QLabel(self.groupBox_6)
        self.label_29.setObjectName(_fromUtf8("label_29"))
        self.horizontalLayout_24.addWidget(self.label_29)
        self.cboLateralStrUsDist = QtGui.QComboBox(self.groupBox_6)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cboLateralStrUsDist.sizePolicy().hasHeightForWidth())
        self.cboLateralStrUsDist.setSizePolicy(sizePolicy)
        self.cboLateralStrUsDist.setObjectName(_fromUtf8("cboLateralStrUsDist"))
        self.horizontalLayout_24.addWidget(self.cboLateralStrUsDist)
        self.verticalLayout_9.addLayout(self.horizontalLayout_24)
        self.horizontalLayout_25 = QtGui.QHBoxLayout()
        self.horizontalLayout_25.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_25.setObjectName(_fromUtf8("horizontalLayout_25"))
        self.label_30 = QtGui.QLabel(self.groupBox_6)
        self.label_30.setObjectName(_fromUtf8("label_30"))
        self.horizontalLayout_25.addWidget(self.label_30)
        self.cboLateralStrTopWidth = QtGui.QComboBox(self.groupBox_6)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cboLateralStrTopWidth.sizePolicy().hasHeightForWidth())
        self.cboLateralStrTopWidth.setSizePolicy(sizePolicy)
        self.cboLateralStrTopWidth.setObjectName(_fromUtf8("cboLateralStrTopWidth"))
        self.horizontalLayout_25.addWidget(self.cboLateralStrTopWidth)
        self.verticalLayout_9.addLayout(self.horizontalLayout_25)
        self.gridLayout_10.addLayout(self.verticalLayout_9, 0, 0, 1, 1)
        self.gridLayout_3.addWidget(self.groupBox_6, 2, 0, 1, 1)
        self.tabWidget.addTab(self.structures, _fromUtf8(""))
        self.storageAreas = QtGui.QWidget()
        self.storageAreas.setObjectName(_fromUtf8("storageAreas"))
        self.gridLayout_11 = QtGui.QGridLayout(self.storageAreas)
        self.gridLayout_11.setMargin(6)
        self.gridLayout_11.setObjectName(_fromUtf8("gridLayout_11"))
        self.verticalLayout_10 = QtGui.QVBoxLayout()
        self.verticalLayout_10.setObjectName(_fromUtf8("verticalLayout_10"))
        self.groupBox_7 = QtGui.QGroupBox(self.storageAreas)
        self.groupBox_7.setObjectName(_fromUtf8("groupBox_7"))
        self.gridLayout_12 = QtGui.QGridLayout(self.groupBox_7)
        self.gridLayout_12.setMargin(3)
        self.gridLayout_12.setObjectName(_fromUtf8("gridLayout_12"))
        self.horizontalLayout_26 = QtGui.QHBoxLayout()
        self.horizontalLayout_26.setObjectName(_fromUtf8("horizontalLayout_26"))
        self.label_31 = QtGui.QLabel(self.groupBox_7)
        self.label_31.setObjectName(_fromUtf8("label_31"))
        self.horizontalLayout_26.addWidget(self.label_31)
        self.cboSALayer = QtGui.QComboBox(self.groupBox_7)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cboSALayer.sizePolicy().hasHeightForWidth())
        self.cboSALayer.setSizePolicy(sizePolicy)
        self.cboSALayer.setObjectName(_fromUtf8("cboSALayer"))
        self.horizontalLayout_26.addWidget(self.cboSALayer)
        self.gridLayout_12.addLayout(self.horizontalLayout_26, 0, 0, 1, 1)
        self.horizontalLayout_27 = QtGui.QHBoxLayout()
        self.horizontalLayout_27.setObjectName(_fromUtf8("horizontalLayout_27"))
        self.label_32 = QtGui.QLabel(self.groupBox_7)
        self.label_32.setObjectName(_fromUtf8("label_32"))
        self.horizontalLayout_27.addWidget(self.label_32)
        self.cboSAName = QtGui.QComboBox(self.groupBox_7)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cboSAName.sizePolicy().hasHeightForWidth())
        self.cboSAName.setSizePolicy(sizePolicy)
        self.cboSAName.setObjectName(_fromUtf8("cboSAName"))
        self.horizontalLayout_27.addWidget(self.cboSAName)
        self.gridLayout_12.addLayout(self.horizontalLayout_27, 1, 0, 1, 1)
        self.verticalLayout_10.addWidget(self.groupBox_7)
        self.groupBox_8 = QtGui.QGroupBox(self.storageAreas)
        self.groupBox_8.setObjectName(_fromUtf8("groupBox_8"))
        self.gridLayout_13 = QtGui.QGridLayout(self.groupBox_8)
        self.gridLayout_13.setMargin(3)
        self.gridLayout_13.setObjectName(_fromUtf8("gridLayout_13"))
        self.horizontalLayout_28 = QtGui.QHBoxLayout()
        self.horizontalLayout_28.setObjectName(_fromUtf8("horizontalLayout_28"))
        self.label_33 = QtGui.QLabel(self.groupBox_8)
        self.label_33.setObjectName(_fromUtf8("label_33"))
        self.horizontalLayout_28.addWidget(self.label_33)
        self.cboSacLayer = QtGui.QComboBox(self.groupBox_8)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cboSacLayer.sizePolicy().hasHeightForWidth())
        self.cboSacLayer.setSizePolicy(sizePolicy)
        self.cboSacLayer.setObjectName(_fromUtf8("cboSacLayer"))
        self.horizontalLayout_28.addWidget(self.cboSacLayer)
        self.gridLayout_13.addLayout(self.horizontalLayout_28, 0, 0, 1, 1)
        self.horizontalLayout_29 = QtGui.QHBoxLayout()
        self.horizontalLayout_29.setObjectName(_fromUtf8("horizontalLayout_29"))
        self.label_34 = QtGui.QLabel(self.groupBox_8)
        self.label_34.setObjectName(_fromUtf8("label_34"))
        self.horizontalLayout_29.addWidget(self.label_34)
        self.cboSacName = QtGui.QComboBox(self.groupBox_8)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cboSacName.sizePolicy().hasHeightForWidth())
        self.cboSacName.setSizePolicy(sizePolicy)
        self.cboSacName.setObjectName(_fromUtf8("cboSacName"))
        self.horizontalLayout_29.addWidget(self.cboSacName)
        self.gridLayout_13.addLayout(self.horizontalLayout_29, 1, 0, 1, 1)
        self.verticalLayout_10.addWidget(self.groupBox_8)
        self.gridLayout_11.addLayout(self.verticalLayout_10, 0, 0, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_11.addItem(spacerItem2, 1, 0, 1, 1)
        self.tabWidget.addTab(self.storageAreas, _fromUtf8(""))
        self.gridLayout.addWidget(self.tabWidget, 1, 0, 1, 1)
        self.buttonBox = QtGui.QDialogButtonBox(importDataIntoRasTables)
        self.buttonBox.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.gridLayout.addWidget(self.buttonBox, 2, 0, 1, 1)
        self.chkOnlySelected = QtGui.QCheckBox(importDataIntoRasTables)
        self.chkOnlySelected.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.chkOnlySelected.setObjectName(_fromUtf8("chkOnlySelected"))
        self.gridLayout.addWidget(self.chkOnlySelected, 0, 0, 1, 1)
        self.label_9.setBuddy(self.cbo2dFlowAreas)
        self.AreaNameAttributeLabel.setBuddy(self.cbo2dAreasNameAttr)
        self.AreaNameAttributeLabel_2.setBuddy(self.cbo2dAreasMeshSizeAttr)
        self.AreaNameAttributeLabel_3.setBuddy(self.cboBreaklines)
        self.AreaNameAttributeLabel_4.setBuddy(self.cboBreaklineCellSizeAlongAttr)

        self.retranslateUi(importDataIntoRasTables)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(importDataIntoRasTables)

    def retranslateUi(self, importDataIntoRasTables):
        importDataIntoRasTables.setWindowTitle(_translate("importDataIntoRasTables", "Import Data Into RAS PostGIS Tables", None))
        self.label.setText(_translate("importDataIntoRasTables", "Rivers Layer", None))
        self.label_35.setText(_translate("importDataIntoRasTables", "River name attribute", None))
        self.label_36.setText(_translate("importDataIntoRasTables", "Reach name attribute", None))
        self.label_2.setText(_translate("importDataIntoRasTables", "Cross-sections Layer", None))
        self.label_4.setText(_translate("importDataIntoRasTables", "Banks Layer", None))
        self.label_7.setText(_translate("importDataIntoRasTables", "Flow Paths Layer", None))
        self.label_8.setText(_translate("importDataIntoRasTables", "Type attribute", None))
        self.label_3.setText(_translate("importDataIntoRasTables", "Levees Layer", None))
        self.label_5.setText(_translate("importDataIntoRasTables", "Ineffective Flow Areas Layer", None))
        self.label_10.setText(_translate("importDataIntoRasTables", "Elevation attribute", None))
        self.label_6.setText(_translate("importDataIntoRasTables", "Blocked Obstructions Layer", None))
        self.label_11.setText(_translate("importDataIntoRasTables", "Elevation attribute", None))
        self.label_12.setText(_translate("importDataIntoRasTables", "Landuse Areas Layer", None))
        self.label_13.setText(_translate("importDataIntoRasTables", "Land Cover Code attribute", None))
        self.label_14.setText(_translate("importDataIntoRasTables", "Manning\'s n attribute", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.general), _translate("importDataIntoRasTables", "General", None))
        self.groupBox.setTitle(_translate("importDataIntoRasTables", "2D Flow Areas", None))
        self.label_9.setText(_translate("importDataIntoRasTables", "Layer name", None))
        self.AreaNameAttributeLabel.setText(_translate("importDataIntoRasTables", "Area name attribute", None))
        self.AreaNameAttributeLabel_2.setText(_translate("importDataIntoRasTables", "Default cell size attribute", None))
        self.groupBox_2.setTitle(_translate("importDataIntoRasTables", "Breaklines", None))
        self.AreaNameAttributeLabel_3.setText(_translate("importDataIntoRasTables", "Layer name", None))
        self.label_15.setText(_translate("importDataIntoRasTables", "Attributes:", None))
        self.AreaNameAttributeLabel_4.setText(_translate("importDataIntoRasTables", "Cell size along a breakline", None))
        self.label_16.setText(_translate("importDataIntoRasTables", "Cell size across a breakline", None))
        self.label_17.setText(_translate("importDataIntoRasTables", "Number of cells rows to align", None))
        self.groupBox_3.setTitle(_translate("importDataIntoRasTables", "Breakpoints", None))
        self.label_18.setText(_translate("importDataIntoRasTables", "Layer name", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.flowAreas), _translate("importDataIntoRasTables", "2D", None))
        self.groupBox_4.setTitle(_translate("importDataIntoRasTables", "Bridges/Culverts", None))
        self.label_19.setText(_translate("importDataIntoRasTables", "Layer name", None))
        self.label_20.setText(_translate("importDataIntoRasTables", "Name attribute", None))
        self.label_21.setText(_translate("importDataIntoRasTables", "US distance attribute", None))
        self.label_22.setText(_translate("importDataIntoRasTables", "Top width attribute", None))
        self.groupBox_5.setTitle(_translate("importDataIntoRasTables", "Inline structures", None))
        self.label_23.setText(_translate("importDataIntoRasTables", "Layer name", None))
        self.label_24.setText(_translate("importDataIntoRasTables", "Name attribute", None))
        self.label_25.setText(_translate("importDataIntoRasTables", "US distance attribute", None))
        self.label_26.setText(_translate("importDataIntoRasTables", "Top width attribute", None))
        self.groupBox_6.setTitle(_translate("importDataIntoRasTables", "Lateral structures", None))
        self.label_27.setText(_translate("importDataIntoRasTables", "Layer name", None))
        self.label_28.setText(_translate("importDataIntoRasTables", "Name attribute", None))
        self.label_29.setText(_translate("importDataIntoRasTables", "US distance attribute", None))
        self.label_30.setText(_translate("importDataIntoRasTables", "Top width attribute", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.structures), _translate("importDataIntoRasTables", "Hydraulic Structures", None))
        self.groupBox_7.setTitle(_translate("importDataIntoRasTables", "Storage Areas", None))
        self.label_31.setText(_translate("importDataIntoRasTables", "Layer name", None))
        self.label_32.setText(_translate("importDataIntoRasTables", "Name attribute", None))
        self.groupBox_8.setTitle(_translate("importDataIntoRasTables", "Storage Area Connections", None))
        self.label_33.setText(_translate("importDataIntoRasTables", "Layer name", None))
        self.label_34.setText(_translate("importDataIntoRasTables", "Name attribute", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.storageAreas), _translate("importDataIntoRasTables", "Storage Areas", None))
        self.chkOnlySelected.setText(_translate("importDataIntoRasTables", "Use selected features if selection exists", None))

