# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/ui_rasXSUpdate.ui'
#
# Created: Sun Oct 11 21:21:13 2015
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_rasXSUpdate(object):
    def setupUi(self, rasXSUpdate):
        rasXSUpdate.setObjectName(_fromUtf8("rasXSUpdate"))
        rasXSUpdate.setWindowModality(QtCore.Qt.WindowModal)
        rasXSUpdate.resize(333, 324)
        self.gridLayout = QtGui.QGridLayout(rasXSUpdate)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.groupBox_2 = QtGui.QGroupBox(rasXSUpdate)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.gridLayout_5 = QtGui.QGridLayout(self.groupBox_2)
        self.gridLayout_5.setMargin(3)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setContentsMargins(-1, -1, -1, 0)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setContentsMargins(-1, -1, -1, 0)
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.label = QtGui.QLabel(self.groupBox_2)
        self.label.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout_5.addWidget(self.label)
        self.cboMeasuredLayer = QtGui.QComboBox(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cboMeasuredLayer.sizePolicy().hasHeightForWidth())
        self.cboMeasuredLayer.setSizePolicy(sizePolicy)
        self.cboMeasuredLayer.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.cboMeasuredLayer.setObjectName(_fromUtf8("cboMeasuredLayer"))
        self.horizontalLayout_5.addWidget(self.cboMeasuredLayer)
        self.verticalLayout_4.addLayout(self.horizontalLayout_5)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.label_2 = QtGui.QLabel(self.groupBox_2)
        self.label_2.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout.addWidget(self.label_2)
        self.cboMeasuredElevation = QtGui.QComboBox(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cboMeasuredElevation.sizePolicy().hasHeightForWidth())
        self.cboMeasuredElevation.setSizePolicy(sizePolicy)
        self.cboMeasuredElevation.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.cboMeasuredElevation.setObjectName(_fromUtf8("cboMeasuredElevation"))
        self.horizontalLayout.addWidget(self.cboMeasuredElevation)
        self.verticalLayout_4.addLayout(self.horizontalLayout)
        self.chkOnlySelected = QtGui.QCheckBox(self.groupBox_2)
        self.chkOnlySelected.setObjectName(_fromUtf8("chkOnlySelected"))
        self.verticalLayout_4.addWidget(self.chkOnlySelected)
        self.gridLayout_5.addLayout(self.verticalLayout_4, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.groupBox_2)
        self.groupBox = QtGui.QGroupBox(rasXSUpdate)
        self.groupBox.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.groupBox.setCheckable(False)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.gridLayout_2 = QtGui.QGridLayout(self.groupBox)
        self.gridLayout_2.setMargin(3)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.groupBanksExt = QtGui.QGroupBox(self.groupBox)
        self.groupBanksExt.setCheckable(True)
        self.groupBanksExt.setObjectName(_fromUtf8("groupBanksExt"))
        self.gridLayout_3 = QtGui.QGridLayout(self.groupBanksExt)
        self.gridLayout_3.setMargin(3)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setContentsMargins(-1, 0, -1, 0)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(-1, -1, -1, 0)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.label_5 = QtGui.QLabel(self.groupBanksExt)
        self.label_5.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayout_3.addWidget(self.label_5)
        self.cboInterpArea = QtGui.QComboBox(self.groupBanksExt)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.cboInterpArea.sizePolicy().hasHeightForWidth())
        self.cboInterpArea.setSizePolicy(sizePolicy)
        self.cboInterpArea.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.cboInterpArea.setObjectName(_fromUtf8("cboInterpArea"))
        self.horizontalLayout_3.addWidget(self.cboInterpArea)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.label_4 = QtGui.QLabel(self.groupBanksExt)
        self.label_4.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.horizontalLayout_2.addWidget(self.label_4)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.xsTol = QtGui.QLineEdit(self.groupBanksExt)
        self.xsTol.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.xsTol.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.xsTol.setObjectName(_fromUtf8("xsTol"))
        self.horizontalLayout_2.addWidget(self.xsTol)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.gridLayout_3.addLayout(self.verticalLayout_2, 0, 0, 1, 1)
        self.gridLayout_2.addWidget(self.groupBanksExt, 0, 0, 1, 1)
        self.groupBathyExt = QtGui.QGroupBox(self.groupBox)
        self.groupBathyExt.setCheckable(True)
        self.groupBathyExt.setChecked(False)
        self.groupBathyExt.setObjectName(_fromUtf8("groupBathyExt"))
        self.gridLayout_4 = QtGui.QGridLayout(self.groupBathyExt)
        self.gridLayout_4.setMargin(3)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setContentsMargins(-1, -1, -1, 0)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.label_3 = QtGui.QLabel(self.groupBathyExt)
        self.label_3.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.verticalLayout_3.addWidget(self.label_3)
        self.cboBathyExtLayer = QtGui.QComboBox(self.groupBathyExt)
        self.cboBathyExtLayer.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.cboBathyExtLayer.setObjectName(_fromUtf8("cboBathyExtLayer"))
        self.verticalLayout_3.addWidget(self.cboBathyExtLayer)
        self.gridLayout_4.addLayout(self.verticalLayout_3, 0, 0, 1, 1)
        self.gridLayout_2.addWidget(self.groupBathyExt, 1, 0, 1, 1)
        self.verticalLayout.addWidget(self.groupBox)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.buttonBox = QtGui.QDialogButtonBox(rasXSUpdate)
        self.buttonBox.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.gridLayout.addWidget(self.buttonBox, 2, 0, 1, 1)

        self.retranslateUi(rasXSUpdate)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), rasXSUpdate.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), rasXSUpdate.reject)
        QtCore.QMetaObject.connectSlotsByName(rasXSUpdate)

    def retranslateUi(self, rasXSUpdate):
        rasXSUpdate.setWindowTitle(_translate("rasXSUpdate", "Update Elevations", None))
        self.groupBox_2.setTitle(_translate("rasXSUpdate", "Bathymetry points", None))
        self.label.setText(_translate("rasXSUpdate", "Layer name", None))
        self.label_2.setText(_translate("rasXSUpdate", "Elevation Attribute", None))
        self.chkOnlySelected.setText(_translate("rasXSUpdate", "Update only selected points", None))
        self.groupBox.setTitle(_translate("rasXSUpdate", "Select interpolation limits", None))
        self.groupBanksExt.setTitle(_translate("rasXSUpdate", "Banks extents", None))
        self.label_5.setText(_translate("rasXSUpdate", "Interpolation Area", None))
        self.label_4.setText(_translate("rasXSUpdate", "XS Tolerance (maps units)", None))
        self.xsTol.setText(_translate("rasXSUpdate", "30", None))
        self.groupBathyExt.setTitle(_translate("rasXSUpdate", "Bathymetry extents", None))
        self.label_3.setText(_translate("rasXSUpdate", "Bathymetry extents layer", None))

