# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui_rivergis.ui'
#
# Created: Tue Mar 24 11:27:21 2015
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_RiverGis0(object):
    def setupUi(self, RiverGis0):
        RiverGis0.setObjectName(_fromUtf8("RiverGis0"))
        RiverGis0.resize(882, 715)
        RiverGis0.setMinimumSize(QtCore.QSize(600, 0))
        font = QtGui.QFont()
        font.setPointSize(8)
        RiverGis0.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/rivergis/icons/rivergis.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        RiverGis0.setWindowIcon(icon)
        self.centralWidget = QtGui.QWidget(RiverGis0)
        self.centralWidget.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralWidget.sizePolicy().hasHeightForWidth())
        self.centralWidget.setSizePolicy(sizePolicy)
        self.centralWidget.setMinimumSize(QtCore.QSize(0, 0))
        self.centralWidget.setMaximumSize(QtCore.QSize(2000, 16777215))
        self.centralWidget.setBaseSize(QtCore.QSize(200, 0))
        self.centralWidget.setObjectName(_fromUtf8("centralWidget"))
        self.gridLayout_2 = QtGui.QGridLayout(self.centralWidget)
        self.gridLayout_2.setMargin(1)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.tabs = QtGui.QTabWidget(self.centralWidget)
        self.tabs.setObjectName(_fromUtf8("tabs"))
        self.srcLayersTab = QtGui.QWidget()
        self.srcLayersTab.setObjectName(_fromUtf8("srcLayersTab"))
        self.gridLayout_14 = QtGui.QGridLayout(self.srcLayersTab)
        self.gridLayout_14.setObjectName(_fromUtf8("gridLayout_14"))
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_14.addItem(spacerItem, 1, 0, 1, 1)
        self.gridLayoutLayers = QtGui.QGridLayout()
        self.gridLayoutLayers.setObjectName(_fromUtf8("gridLayoutLayers"))
        self.loadRasterDemButton = QtGui.QToolButton(self.srcLayersTab)
        self.loadRasterDemButton.setMinimumSize(QtCore.QSize(24, 24))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/rivergis/icons/mActionAddRasterLayer.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.loadRasterDemButton.setIcon(icon1)
        self.loadRasterDemButton.setIconSize(QtCore.QSize(24, 24))
        self.loadRasterDemButton.setObjectName(_fromUtf8("loadRasterDemButton"))
        self.gridLayoutLayers.addWidget(self.loadRasterDemButton, 12, 3, 1, 1)
        self.importXs2RDbButton = QtGui.QToolButton(self.srcLayersTab)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/rivergis/icons/mActionImportToRDb.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.importXs2RDbButton.setIcon(icon2)
        self.importXs2RDbButton.setIconSize(QtCore.QSize(24, 24))
        self.importXs2RDbButton.setObjectName(_fromUtf8("importXs2RDbButton"))
        self.gridLayoutLayers.addWidget(self.importXs2RDbButton, 4, 5, 1, 1)
        self.comboDEM = QtGui.QComboBox(self.srcLayersTab)
        self.comboDEM.setMinimumSize(QtCore.QSize(0, 24))
        self.comboDEM.setMaximumSize(QtCore.QSize(300, 16777215))
        self.comboDEM.setObjectName(_fromUtf8("comboDEM"))
        self.gridLayoutLayers.addWidget(self.comboDEM, 12, 1, 1, 1)
        self.comboRivers = QtGui.QComboBox(self.srcLayersTab)
        self.comboRivers.setMinimumSize(QtCore.QSize(150, 24))
        self.comboRivers.setMaximumSize(QtCore.QSize(300, 16777215))
        self.comboRivers.setObjectName(_fromUtf8("comboRivers"))
        self.gridLayoutLayers.addWidget(self.comboRivers, 3, 1, 1, 1)
        self.importRivers2RDbButton = QtGui.QToolButton(self.srcLayersTab)
        self.importRivers2RDbButton.setIcon(icon2)
        self.importRivers2RDbButton.setIconSize(QtCore.QSize(24, 24))
        self.importRivers2RDbButton.setObjectName(_fromUtf8("importRivers2RDbButton"))
        self.gridLayoutLayers.addWidget(self.importRivers2RDbButton, 3, 5, 1, 1)
        self.loadOgrRiversButton = QtGui.QToolButton(self.srcLayersTab)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/rivergis/icons/mActionAddOgrLayer.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.loadOgrRiversButton.setIcon(icon3)
        self.loadOgrRiversButton.setIconSize(QtCore.QSize(24, 24))
        self.loadOgrRiversButton.setObjectName(_fromUtf8("loadOgrRiversButton"))
        self.gridLayoutLayers.addWidget(self.loadOgrRiversButton, 3, 3, 1, 1)
        self.comboLandCover = QtGui.QComboBox(self.srcLayersTab)
        self.comboLandCover.setMinimumSize(QtCore.QSize(0, 24))
        self.comboLandCover.setMaximumSize(QtCore.QSize(300, 16777215))
        self.comboLandCover.setObjectName(_fromUtf8("comboLandCover"))
        self.gridLayoutLayers.addWidget(self.comboLandCover, 9, 1, 1, 1)
        self.loadOgrLandCoverButton = QtGui.QToolButton(self.srcLayersTab)
        self.loadOgrLandCoverButton.setIcon(icon3)
        self.loadOgrLandCoverButton.setIconSize(QtCore.QSize(24, 24))
        self.loadOgrLandCoverButton.setObjectName(_fromUtf8("loadOgrLandCoverButton"))
        self.gridLayoutLayers.addWidget(self.loadOgrLandCoverButton, 9, 3, 1, 1)
        self.label = QtGui.QLabel(self.srcLayersTab)
        self.label.setMinimumSize(QtCore.QSize(80, 0))
        self.label.setMaximumSize(QtCore.QSize(80, 16777215))
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayoutLayers.addWidget(self.label, 3, 0, 1, 1)
        self.labelDEM = QtGui.QLabel(self.srcLayersTab)
        self.labelDEM.setMaximumSize(QtCore.QSize(80, 16777215))
        self.labelDEM.setObjectName(_fromUtf8("labelDEM"))
        self.gridLayoutLayers.addWidget(self.labelDEM, 12, 0, 1, 1)
        self.populateCombosButton = QtGui.QToolButton(self.srcLayersTab)
        self.populateCombosButton.setMinimumSize(QtCore.QSize(150, 0))
        self.populateCombosButton.setMaximumSize(QtCore.QSize(160000, 16777215))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/rivergis/icons/qgis_icon.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.populateCombosButton.setIcon(icon4)
        self.populateCombosButton.setIconSize(QtCore.QSize(150, 24))
        self.populateCombosButton.setPopupMode(QtGui.QToolButton.DelayedPopup)
        self.populateCombosButton.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.populateCombosButton.setObjectName(_fromUtf8("populateCombosButton"))
        self.gridLayoutLayers.addWidget(self.populateCombosButton, 1, 1, 1, 1)
        self.infoRiversButton = QtGui.QToolButton(self.srcLayersTab)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/rivergis/icons/mActionLayerInfo.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.infoRiversButton.setIcon(icon5)
        self.infoRiversButton.setIconSize(QtCore.QSize(24, 24))
        self.infoRiversButton.setObjectName(_fromUtf8("infoRiversButton"))
        self.gridLayoutLayers.addWidget(self.infoRiversButton, 3, 4, 1, 1)
        self.infoLandCoverButton = QtGui.QToolButton(self.srcLayersTab)
        self.infoLandCoverButton.setIcon(icon5)
        self.infoLandCoverButton.setIconSize(QtCore.QSize(24, 24))
        self.infoLandCoverButton.setObjectName(_fromUtf8("infoLandCoverButton"))
        self.gridLayoutLayers.addWidget(self.infoLandCoverButton, 9, 4, 1, 1)
        self.infoDEMButton = QtGui.QToolButton(self.srcLayersTab)
        self.infoDEMButton.setIcon(icon5)
        self.infoDEMButton.setIconSize(QtCore.QSize(24, 24))
        self.infoDEMButton.setObjectName(_fromUtf8("infoDEMButton"))
        self.gridLayoutLayers.addWidget(self.infoDEMButton, 12, 4, 1, 1)
        self.label_6 = QtGui.QLabel(self.srcLayersTab)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayoutLayers.addWidget(self.label_6, 8, 1, 1, 1)
        self.label_7 = QtGui.QLabel(self.srcLayersTab)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayoutLayers.addWidget(self.label_7, 2, 1, 1, 1)
        self.comboXsections = QtGui.QComboBox(self.srcLayersTab)
        self.comboXsections.setMinimumSize(QtCore.QSize(0, 24))
        self.comboXsections.setMaximumSize(QtCore.QSize(300, 16777215))
        self.comboXsections.setObjectName(_fromUtf8("comboXsections"))
        self.gridLayoutLayers.addWidget(self.comboXsections, 4, 1, 1, 1)
        self.loadOgrXsButton = QtGui.QToolButton(self.srcLayersTab)
        self.loadOgrXsButton.setIcon(icon3)
        self.loadOgrXsButton.setIconSize(QtCore.QSize(24, 24))
        self.loadOgrXsButton.setObjectName(_fromUtf8("loadOgrXsButton"))
        self.gridLayoutLayers.addWidget(self.loadOgrXsButton, 4, 3, 1, 1)
        self.infoXsectionsButton = QtGui.QToolButton(self.srcLayersTab)
        self.infoXsectionsButton.setIcon(icon5)
        self.infoXsectionsButton.setIconSize(QtCore.QSize(24, 24))
        self.infoXsectionsButton.setObjectName(_fromUtf8("infoXsectionsButton"))
        self.gridLayoutLayers.addWidget(self.infoXsectionsButton, 4, 4, 1, 1)
        self.infoBedPointsButton = QtGui.QToolButton(self.srcLayersTab)
        self.infoBedPointsButton.setIcon(icon5)
        self.infoBedPointsButton.setIconSize(QtCore.QSize(24, 24))
        self.infoBedPointsButton.setObjectName(_fromUtf8("infoBedPointsButton"))
        self.gridLayoutLayers.addWidget(self.infoBedPointsButton, 5, 4, 1, 1)
        self.loadOgrBedPointsButton = QtGui.QToolButton(self.srcLayersTab)
        self.loadOgrBedPointsButton.setIcon(icon3)
        self.loadOgrBedPointsButton.setIconSize(QtCore.QSize(24, 24))
        self.loadOgrBedPointsButton.setObjectName(_fromUtf8("loadOgrBedPointsButton"))
        self.gridLayoutLayers.addWidget(self.loadOgrBedPointsButton, 5, 3, 1, 1)
        self.importBedPoints2RDbButton = QtGui.QToolButton(self.srcLayersTab)
        self.importBedPoints2RDbButton.setIcon(icon2)
        self.importBedPoints2RDbButton.setIconSize(QtCore.QSize(24, 24))
        self.importBedPoints2RDbButton.setObjectName(_fromUtf8("importBedPoints2RDbButton"))
        self.gridLayoutLayers.addWidget(self.importBedPoints2RDbButton, 5, 5, 1, 1)
        self.infoLeveesButton = QtGui.QToolButton(self.srcLayersTab)
        self.infoLeveesButton.setIcon(icon5)
        self.infoLeveesButton.setIconSize(QtCore.QSize(24, 24))
        self.infoLeveesButton.setObjectName(_fromUtf8("infoLeveesButton"))
        self.gridLayoutLayers.addWidget(self.infoLeveesButton, 6, 4, 1, 1)
        self.label_2 = QtGui.QLabel(self.srcLayersTab)
        self.label_2.setMinimumSize(QtCore.QSize(0, 0))
        self.label_2.setMaximumSize(QtCore.QSize(80, 16777215))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayoutLayers.addWidget(self.label_2, 4, 0, 1, 1)
        self.labelLandCover = QtGui.QLabel(self.srcLayersTab)
        self.labelLandCover.setMaximumSize(QtCore.QSize(80, 16777215))
        self.labelLandCover.setObjectName(_fromUtf8("labelLandCover"))
        self.gridLayoutLayers.addWidget(self.labelLandCover, 9, 0, 1, 1)
        self.comboBedPoints = QtGui.QComboBox(self.srcLayersTab)
        self.comboBedPoints.setMinimumSize(QtCore.QSize(0, 24))
        self.comboBedPoints.setObjectName(_fromUtf8("comboBedPoints"))
        self.gridLayoutLayers.addWidget(self.comboBedPoints, 5, 1, 1, 1)
        self.label_4 = QtGui.QLabel(self.srcLayersTab)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayoutLayers.addWidget(self.label_4, 5, 0, 1, 1)
        self.label_3 = QtGui.QLabel(self.srcLayersTab)
        self.label_3.setMinimumSize(QtCore.QSize(0, 0))
        self.label_3.setMaximumSize(QtCore.QSize(80, 16777215))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayoutLayers.addWidget(self.label_3, 6, 0, 1, 1)
        self.comboLevees = QtGui.QComboBox(self.srcLayersTab)
        self.comboLevees.setMinimumSize(QtCore.QSize(0, 24))
        self.comboLevees.setMaximumSize(QtCore.QSize(300, 16777215))
        self.comboLevees.setObjectName(_fromUtf8("comboLevees"))
        self.gridLayoutLayers.addWidget(self.comboLevees, 6, 1, 1, 1)
        self.infoBanksButton = QtGui.QToolButton(self.srcLayersTab)
        self.infoBanksButton.setIcon(icon5)
        self.infoBanksButton.setIconSize(QtCore.QSize(24, 24))
        self.infoBanksButton.setObjectName(_fromUtf8("infoBanksButton"))
        self.gridLayoutLayers.addWidget(self.infoBanksButton, 7, 4, 1, 1)
        self.loadOgrLeveesButton = QtGui.QToolButton(self.srcLayersTab)
        self.loadOgrLeveesButton.setIcon(icon3)
        self.loadOgrLeveesButton.setIconSize(QtCore.QSize(24, 24))
        self.loadOgrLeveesButton.setObjectName(_fromUtf8("loadOgrLeveesButton"))
        self.gridLayoutLayers.addWidget(self.loadOgrLeveesButton, 6, 3, 1, 1)
        self.importLevees2RDbButton = QtGui.QToolButton(self.srcLayersTab)
        self.importLevees2RDbButton.setIcon(icon2)
        self.importLevees2RDbButton.setIconSize(QtCore.QSize(24, 24))
        self.importLevees2RDbButton.setObjectName(_fromUtf8("importLevees2RDbButton"))
        self.gridLayoutLayers.addWidget(self.importLevees2RDbButton, 6, 5, 1, 1)
        self.label_5 = QtGui.QLabel(self.srcLayersTab)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayoutLayers.addWidget(self.label_5, 7, 0, 1, 1)
        self.comboBanks = QtGui.QComboBox(self.srcLayersTab)
        self.comboBanks.setMinimumSize(QtCore.QSize(0, 24))
        self.comboBanks.setObjectName(_fromUtf8("comboBanks"))
        self.gridLayoutLayers.addWidget(self.comboBanks, 7, 1, 1, 1)
        self.loadOgrBanksButton = QtGui.QToolButton(self.srcLayersTab)
        self.loadOgrBanksButton.setIcon(icon3)
        self.loadOgrBanksButton.setIconSize(QtCore.QSize(24, 24))
        self.loadOgrBanksButton.setObjectName(_fromUtf8("loadOgrBanksButton"))
        self.gridLayoutLayers.addWidget(self.loadOgrBanksButton, 7, 3, 1, 1)
        self.importBanks2RDbButton = QtGui.QToolButton(self.srcLayersTab)
        self.importBanks2RDbButton.setIcon(icon2)
        self.importBanks2RDbButton.setIconSize(QtCore.QSize(24, 24))
        self.importBanks2RDbButton.setObjectName(_fromUtf8("importBanks2RDbButton"))
        self.gridLayoutLayers.addWidget(self.importBanks2RDbButton, 7, 5, 1, 1)
        self.comboLandCoverAttr = QtGui.QComboBox(self.srcLayersTab)
        self.comboLandCoverAttr.setMinimumSize(QtCore.QSize(0, 24))
        self.comboLandCoverAttr.setObjectName(_fromUtf8("comboLandCoverAttr"))
        self.gridLayoutLayers.addWidget(self.comboLandCoverAttr, 10, 1, 1, 1)
        self.label_8 = QtGui.QLabel(self.srcLayersTab)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayoutLayers.addWidget(self.label_8, 10, 0, 1, 1)
        self.gridLayout_14.addLayout(self.gridLayoutLayers, 0, 0, 1, 1)
        self.tabs.addTab(self.srcLayersTab, _fromUtf8(""))
        self.riversTab = QtGui.QWidget()
        self.riversTab.setObjectName(_fromUtf8("riversTab"))
        self.gridLayout_13 = QtGui.QGridLayout(self.riversTab)
        self.gridLayout_13.setObjectName(_fromUtf8("gridLayout_13"))
        self.tableViewRivers = QgsAttributeTableView(self.riversTab)
        self.tableViewRivers.setEnabled(True)
        self.tableViewRivers.setEditTriggers(QtGui.QAbstractItemView.AnyKeyPressed|QtGui.QAbstractItemView.CurrentChanged|QtGui.QAbstractItemView.DoubleClicked|QtGui.QAbstractItemView.EditKeyPressed)
        self.tableViewRivers.setObjectName(_fromUtf8("tableViewRivers"))
        self.gridLayout_13.addWidget(self.tableViewRivers, 0, 0, 1, 1)
        self.gridLayout_4 = QtGui.QGridLayout()
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.toggleEditingRiversButton = QtGui.QToolButton(self.riversTab)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/rivergis/icons/mActionToggleEditing.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.toggleEditingRiversButton.setIcon(icon6)
        self.toggleEditingRiversButton.setObjectName(_fromUtf8("toggleEditingRiversButton"))
        self.gridLayout_4.addWidget(self.toggleEditingRiversButton, 0, 0, 1, 1)
        self.saveRiversEditsButton = QtGui.QToolButton(self.riversTab)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/rivergis/icons/mActionSaveAllEdits.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.saveRiversEditsButton.setIcon(icon7)
        self.saveRiversEditsButton.setObjectName(_fromUtf8("saveRiversEditsButton"))
        self.gridLayout_4.addWidget(self.saveRiversEditsButton, 0, 1, 1, 1)
        self.gridLayout_13.addLayout(self.gridLayout_4, 1, 0, 1, 1)
        self.tabs.addTab(self.riversTab, _fromUtf8(""))
        self.pointsTab = QtGui.QWidget()
        self.pointsTab.setObjectName(_fromUtf8("pointsTab"))
        self.gridLayout_10 = QtGui.QGridLayout(self.pointsTab)
        self.gridLayout_10.setObjectName(_fromUtf8("gridLayout_10"))
        self.tableViewPoints = QgsAttributeTableView(self.pointsTab)
        self.tableViewPoints.setAlternatingRowColors(True)
        self.tableViewPoints.setSortingEnabled(True)
        self.tableViewPoints.setObjectName(_fromUtf8("tableViewPoints"))
        self.tableViewPoints.horizontalHeader().setMinimumSectionSize(70)
        self.tableViewPoints.verticalHeader().setMinimumSectionSize(18)
        self.tableViewPoints.verticalHeader().setStretchLastSection(True)
        self.gridLayout_10.addWidget(self.tableViewPoints, 0, 0, 1, 1)
        self.gridLayout_7 = QtGui.QGridLayout()
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.toggleEditingPtsButton = QtGui.QToolButton(self.pointsTab)
        self.toggleEditingPtsButton.setIcon(icon6)
        self.toggleEditingPtsButton.setObjectName(_fromUtf8("toggleEditingPtsButton"))
        self.gridLayout_7.addWidget(self.toggleEditingPtsButton, 0, 0, 1, 1)
        self.savePtsEditsButton = QtGui.QToolButton(self.pointsTab)
        self.savePtsEditsButton.setIcon(icon7)
        self.savePtsEditsButton.setObjectName(_fromUtf8("savePtsEditsButton"))
        self.gridLayout_7.addWidget(self.savePtsEditsButton, 0, 1, 1, 1)
        self.gridLayout_10.addLayout(self.gridLayout_7, 1, 0, 1, 1)
        self.tabs.addTab(self.pointsTab, _fromUtf8(""))
        self.xsTab = QtGui.QWidget()
        self.xsTab.setObjectName(_fromUtf8("xsTab"))
        self.gridLayout_12 = QtGui.QGridLayout(self.xsTab)
        self.gridLayout_12.setObjectName(_fromUtf8("gridLayout_12"))
        self.xsPlot = PlotWidget(self.xsTab)
        self.xsPlot.setObjectName(_fromUtf8("xsPlot"))
        self.gridLayout_12.addWidget(self.xsPlot, 0, 0, 1, 1)
        self.showFilteredTool = QtGui.QToolButton(self.xsTab)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/rivergis/icons/mActionShowFiltered.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.showFilteredTool.setIcon(icon8)
        self.showFilteredTool.setIconSize(QtCore.QSize(24, 24))
        self.showFilteredTool.setCheckable(True)
        self.showFilteredTool.setChecked(True)
        self.showFilteredTool.setObjectName(_fromUtf8("showFilteredTool"))
        self.gridLayout_12.addWidget(self.showFilteredTool, 1, 0, 1, 1)
        self.tabs.addTab(self.xsTab, _fromUtf8(""))
        self.leveeTab = QtGui.QWidget()
        self.leveeTab.setObjectName(_fromUtf8("leveeTab"))
        self.gridLayout_3 = QtGui.QGridLayout(self.leveeTab)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.tableView = QgsAttributeTableView(self.leveeTab)
        self.tableView.setObjectName(_fromUtf8("tableView"))
        self.gridLayout_3.addWidget(self.tableView, 0, 0, 1, 1)
        self.gridLayout_8 = QtGui.QGridLayout()
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        self.toggleEditingLeveesButton = QtGui.QToolButton(self.leveeTab)
        self.toggleEditingLeveesButton.setIcon(icon6)
        self.toggleEditingLeveesButton.setObjectName(_fromUtf8("toggleEditingLeveesButton"))
        self.gridLayout_8.addWidget(self.toggleEditingLeveesButton, 0, 0, 1, 1)
        self.saveEditsButton = QtGui.QToolButton(self.leveeTab)
        self.saveEditsButton.setIcon(icon7)
        self.saveEditsButton.setObjectName(_fromUtf8("saveEditsButton"))
        self.gridLayout_8.addWidget(self.saveEditsButton, 0, 1, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout_8, 1, 0, 1, 1)
        self.tabs.addTab(self.leveeTab, _fromUtf8(""))
        self.banksTab = QtGui.QWidget()
        self.banksTab.setObjectName(_fromUtf8("banksTab"))
        self.gridLayout_6 = QtGui.QGridLayout(self.banksTab)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.tableView_2 = QgsAttributeTableView(self.banksTab)
        self.tableView_2.setObjectName(_fromUtf8("tableView_2"))
        self.gridLayout_6.addWidget(self.tableView_2, 0, 0, 1, 1)
        self.gridLayout_9 = QtGui.QGridLayout()
        self.gridLayout_9.setObjectName(_fromUtf8("gridLayout_9"))
        self.toggleEditingBanksButton = QtGui.QToolButton(self.banksTab)
        self.toggleEditingBanksButton.setIcon(icon6)
        self.toggleEditingBanksButton.setObjectName(_fromUtf8("toggleEditingBanksButton"))
        self.gridLayout_9.addWidget(self.toggleEditingBanksButton, 0, 0, 1, 1)
        self.saveBanksEditsButton = QtGui.QToolButton(self.banksTab)
        self.saveBanksEditsButton.setIcon(icon7)
        self.saveBanksEditsButton.setObjectName(_fromUtf8("saveBanksEditsButton"))
        self.gridLayout_9.addWidget(self.saveBanksEditsButton, 0, 1, 1, 1)
        self.gridLayout_6.addLayout(self.gridLayout_9, 1, 0, 1, 1)
        self.tabs.addTab(self.banksTab, _fromUtf8(""))
        self.gridLayout_2.addWidget(self.tabs, 0, 0, 1, 1)
        RiverGis0.setCentralWidget(self.centralWidget)
        self.menubar = QtGui.QMenuBar(RiverGis0)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 882, 18))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuDB = QtGui.QMenu(self.menubar)
        self.menuDB.setObjectName(_fromUtf8("menuDB"))
        self.menuExport_selected = QtGui.QMenu(self.menuDB)
        self.menuExport_selected.setObjectName(_fromUtf8("menuExport_selected"))
        self.menuExport_all_cross_sections_to = QtGui.QMenu(self.menuDB)
        self.menuExport_all_cross_sections_to.setObjectName(_fromUtf8("menuExport_all_cross_sections_to"))
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setObjectName(_fromUtf8("menuHelp"))
        self.menuView = QtGui.QMenu(self.menubar)
        self.menuView.setObjectName(_fromUtf8("menuView"))
        self.menuWindows_Size_and_Positions = QtGui.QMenu(self.menuView)
        self.menuWindows_Size_and_Positions.setObjectName(_fromUtf8("menuWindows_Size_and_Positions"))
        self.menuNetwork = QtGui.QMenu(self.menubar)
        self.menuNetwork.setObjectName(_fromUtf8("menuNetwork"))
        self.menuGeometry = QtGui.QMenu(self.menubar)
        self.menuGeometry.setObjectName(_fromUtf8("menuGeometry"))
        RiverGis0.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(RiverGis0)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        RiverGis0.setStatusBar(self.statusbar)
        self.dockRiversTree = QtGui.QDockWidget(RiverGis0)
        self.dockRiversTree.setMinimumSize(QtCore.QSize(152, 200))
        self.dockRiversTree.setMaximumSize(QtCore.QSize(600, 3000))
        self.dockRiversTree.setFloating(False)
        self.dockRiversTree.setAllowedAreas(QtCore.Qt.LeftDockWidgetArea)
        self.dockRiversTree.setObjectName(_fromUtf8("dockRiversTree"))
        self.dockRiversTreeContents = QtGui.QWidget()
        self.dockRiversTreeContents.setObjectName(_fromUtf8("dockRiversTreeContents"))
        self.gridLayout = QtGui.QGridLayout(self.dockRiversTreeContents)
        self.gridLayout.setMargin(1)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.xsecsTree = QtGui.QTreeView(self.dockRiversTreeContents)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.MinimumExpanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.xsecsTree.sizePolicy().hasHeightForWidth())
        self.xsecsTree.setSizePolicy(sizePolicy)
        self.xsecsTree.setMinimumSize(QtCore.QSize(150, 0))
        self.xsecsTree.setMaximumSize(QtCore.QSize(400, 16777215))
        self.xsecsTree.setBaseSize(QtCore.QSize(200, 0))
        self.xsecsTree.setSelectionMode(QtGui.QAbstractItemView.ExtendedSelection)
        self.xsecsTree.setUniformRowHeights(True)
        self.xsecsTree.setHeaderHidden(True)
        self.xsecsTree.setObjectName(_fromUtf8("xsecsTree"))
        self.xsecsTree.header().setDefaultSectionSize(18)
        self.xsecsTree.header().setMinimumSectionSize(15)
        self.gridLayout.addWidget(self.xsecsTree, 0, 0, 1, 1)
        self.gridLayout_5 = QtGui.QGridLayout()
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.mapPanToSelectedXsTool = QtGui.QToolButton(self.dockRiversTreeContents)
        icon9 = QtGui.QIcon()
        icon9.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/rivergis/icons/panToSelected.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.mapPanToSelectedXsTool.setIcon(icon9)
        self.mapPanToSelectedXsTool.setIconSize(QtCore.QSize(24, 24))
        self.mapPanToSelectedXsTool.setCheckable(True)
        self.mapPanToSelectedXsTool.setChecked(True)
        self.mapPanToSelectedXsTool.setObjectName(_fromUtf8("mapPanToSelectedXsTool"))
        self.gridLayout_5.addWidget(self.mapPanToSelectedXsTool, 0, 1, 1, 1)
        self.mapZoomExtentsTool = QtGui.QToolButton(self.dockRiversTreeContents)
        icon10 = QtGui.QIcon()
        icon10.addPixmap(QtGui.QPixmap(_fromUtf8(":/plugins/rivergis/icons/mActionZoomFullExtent.svg")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.mapZoomExtentsTool.setIcon(icon10)
        self.mapZoomExtentsTool.setIconSize(QtCore.QSize(24, 24))
        self.mapZoomExtentsTool.setObjectName(_fromUtf8("mapZoomExtentsTool"))
        self.gridLayout_5.addWidget(self.mapZoomExtentsTool, 0, 0, 1, 1)
        self.gridLayout.addLayout(self.gridLayout_5, 1, 0, 1, 1)
        self.dockRiversTree.setWidget(self.dockRiversTreeContents)
        RiverGis0.addDockWidget(QtCore.Qt.DockWidgetArea(1), self.dockRiversTree)
        self.dockInfo = QtGui.QDockWidget(RiverGis0)
        self.dockInfo.setMinimumSize(QtCore.QSize(200, 126))
        self.dockInfo.setAllowedAreas(QtCore.Qt.BottomDockWidgetArea|QtCore.Qt.TopDockWidgetArea)
        self.dockInfo.setObjectName(_fromUtf8("dockInfo"))
        self.dockWidgetContents_5 = QtGui.QWidget()
        self.dockWidgetContents_5.setObjectName(_fromUtf8("dockWidgetContents_5"))
        self.gridLayout_11 = QtGui.QGridLayout(self.dockWidgetContents_5)
        self.gridLayout_11.setObjectName(_fromUtf8("gridLayout_11"))
        self.infoTextBrowser = QtGui.QTextBrowser(self.dockWidgetContents_5)
        self.infoTextBrowser.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.infoTextBrowser.setObjectName(_fromUtf8("infoTextBrowser"))
        self.gridLayout_11.addWidget(self.infoTextBrowser, 0, 0, 1, 1)
        self.progressBar = QtGui.QProgressBar(self.dockWidgetContents_5)
        self.progressBar.setMaximumSize(QtCore.QSize(100, 16777215))
        self.progressBar.setProperty("value", 0)
        self.progressBar.setInvertedAppearance(False)
        self.progressBar.setObjectName(_fromUtf8("progressBar"))
        self.gridLayout_11.addWidget(self.progressBar, 1, 0, 1, 1)
        self.dockInfo.setWidget(self.dockWidgetContents_5)
        RiverGis0.addDockWidget(QtCore.Qt.DockWidgetArea(8), self.dockInfo)
        self.actionOpen_SQLite_db = QtGui.QAction(RiverGis0)
        self.actionOpen_SQLite_db.setCheckable(False)
        self.actionOpen_SQLite_db.setObjectName(_fromUtf8("actionOpen_SQLite_db"))
        self.actionImport_ISOK_db = QtGui.QAction(RiverGis0)
        self.actionImport_ISOK_db.setObjectName(_fromUtf8("actionImport_ISOK_db"))
        self.actionImport_RAS_GIS_Import_File = QtGui.QAction(RiverGis0)
        self.actionImport_RAS_GIS_Import_File.setObjectName(_fromUtf8("actionImport_RAS_GIS_Import_File"))
        self.actionImport_GeoRAS_Export_File = QtGui.QAction(RiverGis0)
        self.actionImport_GeoRAS_Export_File.setObjectName(_fromUtf8("actionImport_GeoRAS_Export_File"))
        self.actionImport_Mike_11_rawdata = QtGui.QAction(RiverGis0)
        self.actionImport_Mike_11_rawdata.setObjectName(_fromUtf8("actionImport_Mike_11_rawdata"))
        self.actionImport_Mike_11_network = QtGui.QAction(RiverGis0)
        self.actionImport_Mike_11_network.setObjectName(_fromUtf8("actionImport_Mike_11_network"))
        self.actionCreate_new_SQLite_db = QtGui.QAction(RiverGis0)
        self.actionCreate_new_SQLite_db.setObjectName(_fromUtf8("actionCreate_new_SQLite_db"))
        self.actionExport_sel_rivs_to_SQLite_db = QtGui.QAction(RiverGis0)
        self.actionExport_sel_rivs_to_SQLite_db.setObjectName(_fromUtf8("actionExport_sel_rivs_to_SQLite_db"))
        self.actionExport_Mike_11_rawdata_for_selected_xsections = QtGui.QAction(RiverGis0)
        self.actionExport_Mike_11_rawdata_for_selected_xsections.setObjectName(_fromUtf8("actionExport_Mike_11_rawdata_for_selected_xsections"))
        self.actionExport_Mike_11_processed_for_selected_xsections = QtGui.QAction(RiverGis0)
        self.actionExport_Mike_11_processed_for_selected_xsections.setObjectName(_fromUtf8("actionExport_Mike_11_processed_for_selected_xsections"))
        self.actionExport_Mike_11_rawdata = QtGui.QAction(RiverGis0)
        self.actionExport_Mike_11_rawdata.setObjectName(_fromUtf8("actionExport_Mike_11_rawdata"))
        self.actionExport_Mike_11_processed = QtGui.QAction(RiverGis0)
        self.actionExport_Mike_11_processed.setObjectName(_fromUtf8("actionExport_Mike_11_processed"))
        self.actionExport_HEC_RAS_Import_File = QtGui.QAction(RiverGis0)
        self.actionExport_HEC_RAS_Import_File.setObjectName(_fromUtf8("actionExport_HEC_RAS_Import_File"))
        self.actionExport_HEC_RAS_Export_File = QtGui.QAction(RiverGis0)
        self.actionExport_HEC_RAS_Export_File.setObjectName(_fromUtf8("actionExport_HEC_RAS_Export_File"))
        self.actionExport_SQLite_database = QtGui.QAction(RiverGis0)
        self.actionExport_SQLite_database.setObjectName(_fromUtf8("actionExport_SQLite_database"))
        self.actionExport_Sel_SQLite_database = QtGui.QAction(RiverGis0)
        self.actionExport_Sel_SQLite_database.setObjectName(_fromUtf8("actionExport_Sel_SQLite_database"))
        self.actionImport_Cross_sections = QtGui.QAction(RiverGis0)
        self.actionImport_Cross_sections.setObjectName(_fromUtf8("actionImport_Cross_sections"))
        self.actionSet_Current_DEM = QtGui.QAction(RiverGis0)
        self.actionSet_Current_DEM.setObjectName(_fromUtf8("actionSet_Current_DEM"))
        self.actionSet_Current_Land_Cover = QtGui.QAction(RiverGis0)
        self.actionSet_Current_Land_Cover.setEnabled(True)
        self.actionSet_Current_Land_Cover.setObjectName(_fromUtf8("actionSet_Current_Land_Cover"))
        self.actionExport_Sel_Mike_11_rawdata = QtGui.QAction(RiverGis0)
        self.actionExport_Sel_Mike_11_rawdata.setObjectName(_fromUtf8("actionExport_Sel_Mike_11_rawdata"))
        self.actionExport_Sel_HEC_RAS_GIS_Import_File = QtGui.QAction(RiverGis0)
        self.actionExport_Sel_HEC_RAS_GIS_Import_File.setObjectName(_fromUtf8("actionExport_Sel_HEC_RAS_GIS_Import_File"))
        self.actionExport_Sel_HEC_RAS_GIS_Export_File = QtGui.QAction(RiverGis0)
        self.actionExport_Sel_HEC_RAS_GIS_Export_File.setObjectName(_fromUtf8("actionExport_Sel_HEC_RAS_GIS_Export_File"))
        self.actionEdit_Land_Cover_Codes = QtGui.QAction(RiverGis0)
        self.actionEdit_Land_Cover_Codes.setObjectName(_fromUtf8("actionEdit_Land_Cover_Codes"))
        self.actionImport_Hist_Longitudinal_Profile_Max_Stages = QtGui.QAction(RiverGis0)
        self.actionImport_Hist_Longitudinal_Profile_Max_Stages.setObjectName(_fromUtf8("actionImport_Hist_Longitudinal_Profile_Max_Stages"))
        self.actionImport_Hist_Stage_Hydrograph_Cross_section = QtGui.QAction(RiverGis0)
        self.actionImport_Hist_Stage_Hydrograph_Cross_section.setObjectName(_fromUtf8("actionImport_Hist_Stage_Hydrograph_Cross_section"))
        self.actionImport_Longitudinal_Profile_Max_Discharges = QtGui.QAction(RiverGis0)
        self.actionImport_Longitudinal_Profile_Max_Discharges.setObjectName(_fromUtf8("actionImport_Longitudinal_Profile_Max_Discharges"))
        self.actionImport_Discharge_Hydrograph_Cross_section = QtGui.QAction(RiverGis0)
        self.actionImport_Discharge_Hydrograph_Cross_section.setObjectName(_fromUtf8("actionImport_Discharge_Hydrograph_Cross_section"))
        self.actionImport_Measured_Discharge = QtGui.QAction(RiverGis0)
        self.actionImport_Measured_Discharge.setObjectName(_fromUtf8("actionImport_Measured_Discharge"))
        self.actionImport_River_Centerlines = QtGui.QAction(RiverGis0)
        self.actionImport_River_Centerlines.setObjectName(_fromUtf8("actionImport_River_Centerlines"))
        self.actionImport_Channels = QtGui.QAction(RiverGis0)
        self.actionImport_Channels.setObjectName(_fromUtf8("actionImport_Channels"))
        self.actionImport_Land_Cover = QtGui.QAction(RiverGis0)
        self.actionImport_Land_Cover.setObjectName(_fromUtf8("actionImport_Land_Cover"))
        self.actionImport_Hist_Water_Mark = QtGui.QAction(RiverGis0)
        self.actionImport_Hist_Water_Mark.setObjectName(_fromUtf8("actionImport_Hist_Water_Mark"))
        self.actionAbout = QtGui.QAction(RiverGis0)
        self.actionAbout.setObjectName(_fromUtf8("actionAbout"))
        self.actionManual = QtGui.QAction(RiverGis0)
        self.actionManual.setObjectName(_fromUtf8("actionManual"))
        self.actionVisit_Plugins_Web_Site = QtGui.QAction(RiverGis0)
        self.actionVisit_Plugins_Web_Site.setObjectName(_fromUtf8("actionVisit_Plugins_Web_Site"))
        self.actionDonate = QtGui.QAction(RiverGis0)
        self.actionDonate.setObjectName(_fromUtf8("actionDonate"))
        self.actionAdvanced_Search = QtGui.QAction(RiverGis0)
        self.actionAdvanced_Search.setObjectName(_fromUtf8("actionAdvanced_Search"))
        self.actionDB_Statistics = QtGui.QAction(RiverGis0)
        self.actionDB_Statistics.setObjectName(_fromUtf8("actionDB_Statistics"))
        self.actionDB_Vacuum = QtGui.QAction(RiverGis0)
        self.actionDB_Vacuum.setObjectName(_fromUtf8("actionDB_Vacuum"))
        self.actionUpdate_Cross_sections_Elevations_DEM = QtGui.QAction(RiverGis0)
        self.actionUpdate_Cross_sections_Elevations_DEM.setObjectName(_fromUtf8("actionUpdate_Cross_sections_Elevations_DEM"))
        self.actionUpdate_Cross_sections_Elevations_Points = QtGui.QAction(RiverGis0)
        self.actionUpdate_Cross_sections_Elevations_Points.setObjectName(_fromUtf8("actionUpdate_Cross_sections_Elevations_Points"))
        self.actionImport_Cross_section_Measured_Points = QtGui.QAction(RiverGis0)
        self.actionImport_Cross_section_Measured_Points.setObjectName(_fromUtf8("actionImport_Cross_section_Measured_Points"))
        self.actionCheck_Db_completeness = QtGui.QAction(RiverGis0)
        self.actionCheck_Db_completeness.setObjectName(_fromUtf8("actionCheck_Db_completeness"))
        self.actionUpdate_Cross_sections_Chainages = QtGui.QAction(RiverGis0)
        self.actionUpdate_Cross_sections_Chainages.setObjectName(_fromUtf8("actionUpdate_Cross_sections_Chainages"))
        self.actionUpdate_Cross_sections_Elevations = QtGui.QAction(RiverGis0)
        self.actionUpdate_Cross_sections_Elevations.setObjectName(_fromUtf8("actionUpdate_Cross_sections_Elevations"))
        self.actionSet_Current_DEM_2 = QtGui.QAction(RiverGis0)
        self.actionSet_Current_DEM_2.setObjectName(_fromUtf8("actionSet_Current_DEM_2"))
        self.actionSet_Current_Land_Cover_Layer = QtGui.QAction(RiverGis0)
        self.actionSet_Current_Land_Cover_Layer.setObjectName(_fromUtf8("actionSet_Current_Land_Cover_Layer"))
        self.actionEdit_Cover_Codes = QtGui.QAction(RiverGis0)
        self.actionEdit_Cover_Codes.setObjectName(_fromUtf8("actionEdit_Cover_Codes"))
        self.actionImport_Measured_Bed_Points = QtGui.QAction(RiverGis0)
        self.actionImport_Measured_Bed_Points.setObjectName(_fromUtf8("actionImport_Measured_Bed_Points"))
        self.actionMap_Zoom_Extents = QtGui.QAction(RiverGis0)
        self.actionMap_Zoom_Extents.setObjectName(_fromUtf8("actionMap_Zoom_Extents"))
        self.actionRestore_Plugin_s_Windows_Size_and_Position = QtGui.QAction(RiverGis0)
        self.actionRestore_Plugin_s_Windows_Size_and_Position.setObjectName(_fromUtf8("actionRestore_Plugin_s_Windows_Size_and_Position"))
        self.saveMainWindowStateAction = QtGui.QAction(RiverGis0)
        self.saveMainWindowStateAction.setObjectName(_fromUtf8("saveMainWindowStateAction"))
        self.restoreMainWindowStateAction = QtGui.QAction(RiverGis0)
        self.restoreMainWindowStateAction.setObjectName(_fromUtf8("restoreMainWindowStateAction"))
        self.resetMainWindowStateAction = QtGui.QAction(RiverGis0)
        self.resetMainWindowStateAction.setObjectName(_fromUtf8("resetMainWindowStateAction"))
        self.actionPan_Map_to_Selected_Cross_sections = QtGui.QAction(RiverGis0)
        self.actionPan_Map_to_Selected_Cross_sections.setCheckable(True)
        self.actionPan_Map_to_Selected_Cross_sections.setChecked(True)
        self.actionPan_Map_to_Selected_Cross_sections.setObjectName(_fromUtf8("actionPan_Map_to_Selected_Cross_sections"))
        self.actionShow_Cross_section_Points_Filtered_Out_by_Simplification = QtGui.QAction(RiverGis0)
        self.actionShow_Cross_section_Points_Filtered_Out_by_Simplification.setCheckable(True)
        self.actionShow_Cross_section_Points_Filtered_Out_by_Simplification.setChecked(True)
        self.actionShow_Cross_section_Points_Filtered_Out_by_Simplification.setObjectName(_fromUtf8("actionShow_Cross_section_Points_Filtered_Out_by_Simplification"))
        self.actionClean_Map_Layer_Registry = QtGui.QAction(RiverGis0)
        self.actionClean_Map_Layer_Registry.setObjectName(_fromUtf8("actionClean_Map_Layer_Registry"))
        self.actionCreate_Indexes = QtGui.QAction(RiverGis0)
        self.actionCreate_Indexes.setObjectName(_fromUtf8("actionCreate_Indexes"))
        self.actionAaa = QtGui.QAction(RiverGis0)
        self.actionAaa.setEnabled(False)
        self.actionAaa.setObjectName(_fromUtf8("actionAaa"))
        self.actionCreateTopology = QtGui.QAction(RiverGis0)
        self.actionCreateTopology.setObjectName(_fromUtf8("actionCreateTopology"))
        self.actionUpdate_Selected_Cross_sections_Points_from_DEM = QtGui.QAction(RiverGis0)
        self.actionUpdate_Selected_Cross_sections_Points_from_DEM.setObjectName(_fromUtf8("actionUpdate_Selected_Cross_sections_Points_from_DEM"))
        self.actionAdd_measured_Points_to_Cross_sections = QtGui.QAction(RiverGis0)
        self.actionAdd_measured_Points_to_Cross_sections.setObjectName(_fromUtf8("actionAdd_measured_Points_to_Cross_sections"))
        self.actionDelete_Selected_Cross_sections_Points = QtGui.QAction(RiverGis0)
        self.actionDelete_Selected_Cross_sections_Points.setObjectName(_fromUtf8("actionDelete_Selected_Cross_sections_Points"))
        self.actionDelete_Marker_Points = QtGui.QAction(RiverGis0)
        self.actionDelete_Marker_Points.setObjectName(_fromUtf8("actionDelete_Marker_Points"))
        self.actionReset_Marker_Points = QtGui.QAction(RiverGis0)
        self.actionReset_Marker_Points.setObjectName(_fromUtf8("actionReset_Marker_Points"))
        self.actionExport_Points_to_ISOKP = QtGui.QAction(RiverGis0)
        self.actionExport_Points_to_ISOKP.setObjectName(_fromUtf8("actionExport_Points_to_ISOKP"))
        self.menuExport_selected.addAction(self.actionExport_SQLite_database)
        self.menuExport_selected.addAction(self.actionExport_Mike_11_rawdata)
        self.menuExport_selected.addAction(self.actionExport_Mike_11_processed)
        self.menuExport_selected.addAction(self.actionExport_HEC_RAS_Import_File)
        self.menuExport_selected.addAction(self.actionExport_HEC_RAS_Export_File)
        self.menuExport_all_cross_sections_to.addAction(self.actionExport_Sel_SQLite_database)
        self.menuExport_all_cross_sections_to.addAction(self.actionExport_Sel_Mike_11_rawdata)
        self.menuExport_all_cross_sections_to.addAction(self.actionExport_Sel_HEC_RAS_GIS_Import_File)
        self.menuExport_all_cross_sections_to.addAction(self.actionExport_Sel_HEC_RAS_GIS_Export_File)
        self.menuDB.addSeparator()
        self.menuDB.addAction(self.actionCreate_new_SQLite_db)
        self.menuDB.addAction(self.actionOpen_SQLite_db)
        self.menuDB.addSeparator()
        self.menuDB.addAction(self.actionImport_River_Centerlines)
        self.menuDB.addAction(self.actionImport_Cross_sections)
        self.menuDB.addAction(self.actionImport_Measured_Bed_Points)
        self.menuDB.addSeparator()
        self.menuDB.addAction(self.actionImport_RAS_GIS_Import_File)
        self.menuDB.addAction(self.actionImport_GeoRAS_Export_File)
        self.menuDB.addSeparator()
        self.menuDB.addAction(self.actionImport_ISOK_db)
        self.menuDB.addAction(self.actionImport_Mike_11_rawdata)
        self.menuDB.addAction(self.actionImport_Mike_11_network)
        self.menuDB.addSeparator()
        self.menuDB.addAction(self.actionExport_Points_to_ISOKP)
        self.menuDB.addAction(self.menuExport_selected.menuAction())
        self.menuDB.addAction(self.menuExport_all_cross_sections_to.menuAction())
        self.menuDB.addSeparator()
        self.menuDB.addAction(self.actionDB_Statistics)
        self.menuDB.addSeparator()
        self.menuDB.addAction(self.actionCreate_Indexes)
        self.menuHelp.addAction(self.actionManual)
        self.menuHelp.addAction(self.actionVisit_Plugins_Web_Site)
        self.menuHelp.addAction(self.actionAbout)
        self.menuWindows_Size_and_Positions.addAction(self.saveMainWindowStateAction)
        self.menuWindows_Size_and_Positions.addAction(self.restoreMainWindowStateAction)
        self.menuWindows_Size_and_Positions.addAction(self.resetMainWindowStateAction)
        self.menuView.addAction(self.actionMap_Zoom_Extents)
        self.menuView.addAction(self.actionPan_Map_to_Selected_Cross_sections)
        self.menuView.addAction(self.actionShow_Cross_section_Points_Filtered_Out_by_Simplification)
        self.menuView.addSeparator()
        self.menuView.addAction(self.menuWindows_Size_and_Positions.menuAction())
        self.menuNetwork.addAction(self.actionCreateTopology)
        self.menuGeometry.addAction(self.actionUpdate_Selected_Cross_sections_Points_from_DEM)
        self.menuGeometry.addAction(self.actionDelete_Selected_Cross_sections_Points)
        self.menuGeometry.addSeparator()
        self.menuGeometry.addAction(self.actionAdd_measured_Points_to_Cross_sections)
        self.menuGeometry.addAction(self.actionReset_Marker_Points)
        self.menuGeometry.addAction(self.actionDelete_Marker_Points)
        self.menubar.addAction(self.menuDB.menuAction())
        self.menubar.addAction(self.menuNetwork.menuAction())
        self.menubar.addAction(self.menuGeometry.menuAction())
        self.menubar.addAction(self.menuView.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(RiverGis0)
        self.tabs.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(RiverGis0)

    def retranslateUi(self, RiverGis0):
        RiverGis0.setWindowTitle(_translate("RiverGis0", "RiverGIS0", None))
        self.loadRasterDemButton.setText(_translate("RiverGis0", "...", None))
        self.importXs2RDbButton.setToolTip(_translate("RiverGis0", "Import selected layer to current River Database.", None))
        self.importXs2RDbButton.setText(_translate("RiverGis0", "...", None))
        self.importRivers2RDbButton.setToolTip(_translate("RiverGis0", "Import selected layer to current River Database.", None))
        self.importRivers2RDbButton.setText(_translate("RiverGis0", "...", None))
        self.loadOgrRiversButton.setToolTip(_translate("RiverGis0", "Load OGR layer (i.e. Shapefile)", None))
        self.loadOgrRiversButton.setText(_translate("RiverGis0", "...", None))
        self.loadOgrLandCoverButton.setToolTip(_translate("RiverGis0", "Load OGR layer (i.e. Shapefile)", None))
        self.loadOgrLandCoverButton.setText(_translate("RiverGis0", "...", None))
        self.label.setText(_translate("RiverGis0", "Rivers", None))
        self.labelDEM.setText(_translate("RiverGis0", "DEM", None))
        self.populateCombosButton.setToolTip(_translate("RiverGis0", "Load layers from current QGIS project", None))
        self.populateCombosButton.setText(_translate("RiverGis0", "Show layers from QGIS", None))
        self.infoRiversButton.setToolTip(_translate("RiverGis0", "View Layer Info (Metadata)", None))
        self.infoRiversButton.setText(_translate("RiverGis0", "Display Layer Info (Metadata)", None))
        self.infoLandCoverButton.setToolTip(_translate("RiverGis0", "View Layer Info (Metadata)", None))
        self.infoLandCoverButton.setText(_translate("RiverGis0", "...", None))
        self.infoDEMButton.setToolTip(_translate("RiverGis0", "View Layer Info (Metadata)", None))
        self.infoDEMButton.setText(_translate("RiverGis0", "...", None))
        self.label_6.setText(_translate("RiverGis0", "Current layers for probing", None))
        self.label_7.setText(_translate("RiverGis0", "Import layers to RiverDB", None))
        self.loadOgrXsButton.setToolTip(_translate("RiverGis0", "Load OGR layer (i.e. Shapefile)", None))
        self.loadOgrXsButton.setText(_translate("RiverGis0", "...", None))
        self.infoXsectionsButton.setToolTip(_translate("RiverGis0", "View Layer Info (Metadata)", None))
        self.infoXsectionsButton.setText(_translate("RiverGis0", "...", None))
        self.infoBedPointsButton.setToolTip(_translate("RiverGis0", "View Layer Info (Metadata)", None))
        self.infoBedPointsButton.setText(_translate("RiverGis0", "...", None))
        self.loadOgrBedPointsButton.setText(_translate("RiverGis0", "...", None))
        self.importBedPoints2RDbButton.setText(_translate("RiverGis0", "...", None))
        self.infoLeveesButton.setToolTip(_translate("RiverGis0", "View Layer Info (Metadata)", None))
        self.infoLeveesButton.setText(_translate("RiverGis0", "...", None))
        self.label_2.setText(_translate("RiverGis0", "Cross-sections", None))
        self.labelLandCover.setText(_translate("RiverGis0", "Land Cover", None))
        self.label_4.setText(_translate("RiverGis0", "Bed Points", None))
        self.label_3.setText(_translate("RiverGis0", "Levees", None))
        self.infoBanksButton.setText(_translate("RiverGis0", "...", None))
        self.loadOgrLeveesButton.setToolTip(_translate("RiverGis0", "Load OGR layer (i.e. Shapefile)", None))
        self.loadOgrLeveesButton.setText(_translate("RiverGis0", "...", None))
        self.importLevees2RDbButton.setToolTip(_translate("RiverGis0", "Import selected layer to current River Database.", None))
        self.importLevees2RDbButton.setText(_translate("RiverGis0", "...", None))
        self.label_5.setText(_translate("RiverGis0", "Banks", None))
        self.loadOgrBanksButton.setText(_translate("RiverGis0", "...", None))
        self.importBanks2RDbButton.setText(_translate("RiverGis0", "...", None))
        self.label_8.setText(_translate("RiverGis0", "    Cover Attribute", None))
        self.tabs.setTabText(self.tabs.indexOf(self.srcLayersTab), _translate("RiverGis0", "Source Layers", None))
        self.toggleEditingRiversButton.setText(_translate("RiverGis0", "...", None))
        self.saveRiversEditsButton.setText(_translate("RiverGis0", "...", None))
        self.tabs.setTabText(self.tabs.indexOf(self.riversTab), _translate("RiverGis0", "Rivers Table", None))
        self.toggleEditingPtsButton.setText(_translate("RiverGis0", "...", None))
        self.savePtsEditsButton.setText(_translate("RiverGis0", "...", None))
        self.tabs.setTabText(self.tabs.indexOf(self.pointsTab), _translate("RiverGis0", "Points Table", None))
        self.showFilteredTool.setToolTip(_translate("RiverGis0", "Toggle Show Filtered Points. ", None))
        self.showFilteredTool.setText(_translate("RiverGis0", "ShowF", None))
        self.tabs.setTabText(self.tabs.indexOf(self.xsTab), _translate("RiverGis0", "Cross-section", None))
        self.toggleEditingLeveesButton.setText(_translate("RiverGis0", "...", None))
        self.saveEditsButton.setText(_translate("RiverGis0", "...", None))
        self.tabs.setTabText(self.tabs.indexOf(self.leveeTab), _translate("RiverGis0", "Levees", None))
        self.toggleEditingBanksButton.setText(_translate("RiverGis0", "...", None))
        self.saveBanksEditsButton.setText(_translate("RiverGis0", "...", None))
        self.tabs.setTabText(self.tabs.indexOf(self.banksTab), _translate("RiverGis0", "Banks", None))
        self.menuDB.setTitle(_translate("RiverGis0", "DB", None))
        self.menuExport_selected.setTitle(_translate("RiverGis0", "Export selected cross-sections to", None))
        self.menuExport_all_cross_sections_to.setTitle(_translate("RiverGis0", "Export all cross-sections to", None))
        self.menuHelp.setTitle(_translate("RiverGis0", "Help", None))
        self.menuView.setTitle(_translate("RiverGis0", "View", None))
        self.menuWindows_Size_and_Positions.setTitle(_translate("RiverGis0", "Windows Size and Positions", None))
        self.menuNetwork.setTitle(_translate("RiverGis0", "Network", None))
        self.menuGeometry.setTitle(_translate("RiverGis0", "Geometry", None))
        self.dockRiversTree.setWindowTitle(_translate("RiverGis0", "Rivers Tree", None))
        self.mapPanToSelectedXsTool.setText(_translate("RiverGis0", "FS", None))
        self.mapZoomExtentsTool.setText(_translate("RiverGis0", "ZE", None))
        self.dockInfo.setWindowTitle(_translate("RiverGis0", "Info", None))
        self.actionOpen_SQLite_db.setText(_translate("RiverGis0", "Open SQLite Database", None))
        self.actionOpen_SQLite_db.setShortcut(_translate("RiverGis0", "Ctrl+O", None))
        self.actionImport_ISOK_db.setText(_translate("RiverGis0", "Import MySQL Database (ISOK)", None))
        self.actionImport_RAS_GIS_Import_File.setText(_translate("RiverGis0", "Import HEC-RAS GIS Import File", None))
        self.actionImport_GeoRAS_Export_File.setText(_translate("RiverGis0", "Import HEC-RAS GIS Export File", None))
        self.actionImport_Mike_11_rawdata.setText(_translate("RiverGis0", "Import Mike 11 rawdata", None))
        self.actionImport_Mike_11_network.setText(_translate("RiverGis0", "Import Mike 11 network", None))
        self.actionCreate_new_SQLite_db.setText(_translate("RiverGis0", "Create new SQLite Database", None))
        self.actionExport_sel_rivs_to_SQLite_db.setText(_translate("RiverGis0", "Export selected rivers to SQLite database", None))
        self.actionExport_Mike_11_rawdata_for_selected_xsections.setText(_translate("RiverGis0", "Export Mike 11 rawdata for selected xsections", None))
        self.actionExport_Mike_11_processed_for_selected_xsections.setText(_translate("RiverGis0", "Export Mike 11 processed for selected xsections", None))
        self.actionExport_Mike_11_rawdata.setText(_translate("RiverGis0", "Mike 11 rawdata", None))
        self.actionExport_Mike_11_processed.setText(_translate("RiverGis0", "Mike 11 processed", None))
        self.actionExport_HEC_RAS_Import_File.setText(_translate("RiverGis0", "HEC-RAS GIS Import File", None))
        self.actionExport_HEC_RAS_Export_File.setText(_translate("RiverGis0", "HEC-RAS GIS Export File", None))
        self.actionExport_SQLite_database.setText(_translate("RiverGis0", "SQLite database", None))
        self.actionExport_Sel_SQLite_database.setText(_translate("RiverGis0", "SQLite database", None))
        self.actionImport_Cross_sections.setText(_translate("RiverGis0", "Import Cross-sections Linestrings", None))
        self.actionSet_Current_DEM.setText(_translate("RiverGis0", "Set Current DEM", None))
        self.actionSet_Current_Land_Cover.setText(_translate("RiverGis0", "Set Current Land Cover Layer", None))
        self.actionExport_Sel_Mike_11_rawdata.setText(_translate("RiverGis0", "Mike 11 rawdata", None))
        self.actionExport_Sel_HEC_RAS_GIS_Import_File.setText(_translate("RiverGis0", "HEC-RAS GIS Import File", None))
        self.actionExport_Sel_HEC_RAS_GIS_Export_File.setText(_translate("RiverGis0", "HEC-RAS GIS Export File", None))
        self.actionEdit_Land_Cover_Codes.setText(_translate("RiverGis0", "Edit Land Cover Codes", None))
        self.actionImport_Hist_Longitudinal_Profile_Max_Stages.setText(_translate("RiverGis0", "Longitudinal Profile of Max Stages", None))
        self.actionImport_Hist_Stage_Hydrograph_Cross_section.setText(_translate("RiverGis0", "Stage Hydrograph at a Cross-section", None))
        self.actionImport_Longitudinal_Profile_Max_Discharges.setText(_translate("RiverGis0", "Longitudinal Profile Max", None))
        self.actionImport_Discharge_Hydrograph_Cross_section.setText(_translate("RiverGis0", "Discharge Hydrograph at a Cross-section", None))
        self.actionImport_Measured_Discharge.setText(_translate("RiverGis0", "Measured Discharge (i.e. ADCP)", None))
        self.actionImport_River_Centerlines.setText(_translate("RiverGis0", "Import River Centerline Linestrings", None))
        self.actionImport_Channels.setText(_translate("RiverGis0", "Import Channel Polygons", None))
        self.actionImport_Land_Cover.setText(_translate("RiverGis0", "Import Land Cover Polygons", None))
        self.actionImport_Hist_Water_Mark.setText(_translate("RiverGis0", "Water Mark", None))
        self.actionAbout.setText(_translate("RiverGis0", "About", None))
        self.actionManual.setText(_translate("RiverGis0", "Manual", None))
        self.actionVisit_Plugins_Web_Site.setText(_translate("RiverGis0", "Visit Plugin\'s Web Site", None))
        self.actionDonate.setText(_translate("RiverGis0", "Donate", None))
        self.actionAdvanced_Search.setText(_translate("RiverGis0", "Advanced Search", None))
        self.actionDB_Statistics.setText(_translate("RiverGis0", "DB Statistics", None))
        self.actionDB_Vacuum.setText(_translate("RiverGis0", "DB Vacuum", None))
        self.actionUpdate_Cross_sections_Elevations_DEM.setText(_translate("RiverGis0", "Update Cross-sections Elevations from DEM", None))
        self.actionUpdate_Cross_sections_Elevations_Points.setText(_translate("RiverGis0", "Update Cross-sections Elevations from Measured River Bed Points", None))
        self.actionImport_Cross_section_Measured_Points.setText(_translate("RiverGis0", "Import Cross-section Measured Points", None))
        self.actionCheck_Db_completeness.setText(_translate("RiverGis0", "Check Db completeness", None))
        self.actionUpdate_Cross_sections_Chainages.setText(_translate("RiverGis0", "Update Chainages", None))
        self.actionUpdate_Cross_sections_Elevations.setText(_translate("RiverGis0", "Update Elevations", None))
        self.actionSet_Current_DEM_2.setText(_translate("RiverGis0", "Set Current DEM", None))
        self.actionSet_Current_Land_Cover_Layer.setText(_translate("RiverGis0", "Set Current Land Cover Layer", None))
        self.actionEdit_Cover_Codes.setText(_translate("RiverGis0", "Edit Cover Codes and Resistances", None))
        self.actionImport_Measured_Bed_Points.setText(_translate("RiverGis0", "Import Measured Bed Points", None))
        self.actionMap_Zoom_Extents.setText(_translate("RiverGis0", "Map Zoom Extents", None))
        self.actionRestore_Plugin_s_Windows_Size_and_Position.setText(_translate("RiverGis0", "Restore Plugin\'s Windows Size and Position", None))
        self.saveMainWindowStateAction.setText(_translate("RiverGis0", "Save", None))
        self.restoreMainWindowStateAction.setText(_translate("RiverGis0", "Restore", None))
        self.resetMainWindowStateAction.setText(_translate("RiverGis0", "Reset", None))
        self.actionPan_Map_to_Selected_Cross_sections.setText(_translate("RiverGis0", "Pan Map to Selected Cross-sections", None))
        self.actionShow_Cross_section_Points_Filtered_Out_by_Simplification.setText(_translate("RiverGis0", "Show Cross-section Points Filtered Out by Simplification", None))
        self.actionClean_Map_Layer_Registry.setText(_translate("RiverGis0", "Clean Map Layer_Registry", None))
        self.actionCreate_Indexes.setText(_translate("RiverGis0", "Create Indexes", None))
        self.actionAaa.setText(_translate("RiverGis0", "aaa", None))
        self.actionCreateTopology.setText(_translate("RiverGis0", "Create Topology", None))
        self.actionUpdate_Selected_Cross_sections_Points_from_DEM.setText(_translate("RiverGis0", "Update Selected Cross-sections\' Points from DEM", None))
        self.actionAdd_measured_Points_to_Cross_sections.setText(_translate("RiverGis0", "Add measured Points to Cross-sections", None))
        self.actionDelete_Selected_Cross_sections_Points.setText(_translate("RiverGis0", "Delete Selected Cross-sections\' Points", None))
        self.actionDelete_Marker_Points.setText(_translate("RiverGis0", "Delete Marker Points", None))
        self.actionReset_Marker_Points.setText(_translate("RiverGis0", "Reset Marker Points", None))
        self.actionExport_Points_to_ISOKP.setText(_translate("RiverGis0", "Export Points to ISOKP", None))

from pyqtgraph import PlotWidget
from qgis.gui import QgsAttributeTableView
import resources_rc
